simpeg/simpeg

- setup.py
This should really be dependent on Cython, if we're going to call `cythonize` directly in the build script, and if Cython is needed for good performance. Or, if not, we would need to make the import of `cythonize` conditional, and then skip building the extension if Cython isn't installed. Alternatively, don't build the .pyx file, and check in a compiled .c file; then make the following changes to setup.py:
- replace `from Cython.Build import cythonize` on Line 10 with `from setuptools.extension import Extension`
- replace `ext_modules = cythonize('SimPEG/Utils/interputils_cython.pyx')` on Line 53 with `ext_modules = [Extension('interputils_cython', sources=['SimPEG/Utils/interputils_cython.c'])]`
> Add Cython dependency

- SimPEG/Utils/codeutils.py
Making this change would make SimPEG more compatible with multiple inheritance in outside code. Metaclass inheritance is tricky, and for the moment the SimPEG metaclass doesn't really do anything. Setting `SimPEGMetaClass = type` preserves all the existing functionality in SimPEG code, and plays a bit better with outside multiple inheritance involving metaclasses. In the future, this may need to be addressed in more detail.
> Be compatible with outside metaclasses, for now

- docs/index.rst
put examples near the top of the docs
> move examples right after getting started with SimPEG

- SimPEG/Maps.py
- SimPEG/Regularization.py
- tests/base/test_regularization.py
- Meshlesses Identity Map (takes nP instead of a mesh)
- Tikhonov regularization if active cells are used (don't take derivs across interfaces between active cells and not)
- testing improvements: test 1D, 2D, 3D on a random tensor mesh , also test that for a constant mref, phi_m(ref) = 0
(closes #78)
> Meshless Identity Map, Regularization for Active Cell models 

- SimPEG/Examples/EM_FDEM_1D_Inversion.py
- SimPEG/Examples/EM_TDEM_1D_Inversion.py
- SimPEG/Maps.py
- tests/base/test_maps.py
- tests/em/tdem/test_TDEM_b_DerivAdjoint.py
- tests/em/tdem/test_TDEM_b_MultiSrc_DerivAdjoint.py
- tests/em/tdem/test_TDEM_combos.py
- tests/em/tdem/test_TDEM_forward_Analytic.py
- FullMap --> SurjectFull
- Vertical1DMap --> SurjectVertical1D
- Map2Dto3D --> Surject2Dto3D
- ActiveCells --> InjectActiveCells
- ActiveCellsTopo --> InjectActiveCellsTopo
to close #231 
@rowanc1 , @sgkang , @grosenkj : what do you guys think of this?
(I left ExpMap, IdentityMap, #231 talks about dropping the `Map` at the end, but this is a bit of a pain, and I do like having a verb in the name --> each of the maps is doing something, Mapping, Surjecting, Injecting)
> Naming conventions in Maps (re #231)

- SimPEG/DCIP/BaseDC.py
- SimPEG/DCIP/BaseIP.py
- SimPEG/DataMisfit.py
- SimPEG/Directives.py
- SimPEG/EM/FDEM/SurveyFDEM.py
- SimPEG/EM/TDEM/BaseTDEM.py
- SimPEG/FLOW/Richards/RichardsProblem.py
- SimPEG/InvProblem.py
- SimPEG/MT/BaseMT.py
- SimPEG/MT/SurveyMT.py
- SimPEG/Problem.py
- SimPEG/Survey.py
- tests/flow/test_Richards.py
Problem.Jvec, Problem.Jtvec, Problem.fields, DataMisfit,  survey.dpred all take a fields object, `f` not a solution vector `u`. DCIP will take some more clean-up, but this will be handled in the refactor of DC. These changes will close #271. This touches a lot of the repo, so a quick review by a few people would be much appreciated!
> use `f` for fields and `u` for a solution vector

- SimPEG/Optimization.py
The current implementation does not allow you to move off the
bounds (lower/upper) once you have gotten on them, this allows you
to move off of the bound.
Please note that more testing should be done to ensure that this does
not introduce oscillations into the optimization routine.
> Allow moving off bounds in projected gradient

- SimPEG/Regularization.py
- tests/base/test_regularization.py
If no mapping provided and indActive provided, make sure the mapping is the size of number of active cells
> if mapping is none, create an identity map that is size indactive.nonzero

- setup.py
When we go to install SimPEG (or packages w/ SimPEG dependencies) on architecture that doesn't have `numpy` present already, it will fail to install. This happens because `setup.py` imports `numpy` before it's guaranteed to be setup on the system. This change implements a workaround that lets `distutils` get up and going before `numpy` is imported.
See [StackOverflow](http://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py)
> Installation (i.e., setup.py) is no longer dependent on Numpy

- SimPEG/Mesh/CylMesh.py
- tests/em/fdem/forward/test_FDEM_analytics.py
- tests/em/fdem/forward/test_FDEM_casing.py
- tests/em/tdem/test_TDEM_forward_Analytic.py
- tests/mesh/test_cylMesh.py
- tests/mesh/test_operators.py
- bug fix in `aveE2CC` and `aveE2CCV` that was dividing everything by 2 to close #367 
- testing on `aveE2CC`, `aveE2CCV`, `aveF2CC`, `aveF2CCV`
@micmitch : can you take a look at this? If you have any questions / anything is unclear, please let me know!
> bug fix and additional testing on cyl mesh

- SimPEG/Props.py
- tests/base/test_Props.py
Because the properties are setup on class `__new__`, the change
notification was firing and deleting some defaults leading to
unexpected (and difficult to track down) behavior.
> Only clear the maps and props if the change is not undefined.

- .travis.yml
- build universal wheel for SimPEG on travis whenever a tag is submitted
- similar to simpeg/discretize#44, however since SimPEG is now pure python, a universal wheel can instead be used. https://packaging.python.org/distributing/#universal-wheels
> distribution

- SimPEG/ObjectiveFunction.py
- SimPEG/Regularization.py
- tests/base/test_Objectivefct.py
- bring multipliers to top level namespace for objective functions (includes the addition of a setter)
- add np.float64 to acceptable multiplier types 
Now you can change multipliers if you would like to update the multipliers of the objective functions, you can do so from the top level namespace cc @fourndo 
```python
phi1 = ObjectiveFunction.L2ObjectiveFunction(nP=nP)
phi2 = ObjectiveFunction.L2ObjectiveFunction(nP=nP)
phi3 = 2*phi1 + 4*phi2
assert(all(phi3.multipliers == np.r_[2, 4]))
multipliers[1] = 3
assert(all(phi3.multipliers == np.r_[2, 3]))
multipliers = np.r_[1., 5.]
assert(all(phi3.multipliers == np.r_[1., 5.]))
```
> Objective function Multipliers

- docs/conf.py
- update sphinx-gallery to include a backreferences_dir variable as per sphinx-gallery/sphinx-gallery#151
- right now, we are not using `backreferences_dir`. For examples of how we could, see http://sphinx-gallery.readthedocs.io/en/stable/index.html#examples-using-numpy-linspace
> examples gallery

- examples/07-fdem/plot_loop_loop_2Dinversion.py
Generate an example where we invert secondary magnetic field data from a single frequency loop-loop EM survey. We use a horizontal co-planar orientation with three different source-receiver offsets. 
The forward modelling is performed in 3D, but the inversion model is 2D. 
This example was inspired from http://onlinelibrary.wiley.com/doi/10.1002/2013WR014864/full.  
The notebook that will be built in the documentation is here: 
[plot_loop_loop_2Dinversion.ipynb.zip](https://github.com/simpeg/simpeg/files/1778268/plot_loop_loop_2Dinversion.ipynb.zip) 
and the documentation of that example is here: 
[2D inversion of Loop-Loop EM Data — SimPEG 0.7.2 documentation.pdf](https://github.com/simpeg/simpeg/files/1778761/2D.inversion.of.Loop-Loop.EM.Data.SimPEG.0.7.2.documentation.pdf)
@sgkang, …
> Loop-loop 2D EM inversion

- .travis.yml
- SimPEG/Fields.py
- SimPEG/Utils/printinfo.py
- docs/conf.py
- docs/content/api_core/api_Utils.rst
- examples/06-dc/plot_dc_schlumberger_array.py
- examples/07-fdem/plot_loop_loop_2Dinversion.py
- examples/09-tdem/plot_inductive_src_permeable_target.py
- requirements_dev.txt
- tests/utils/test_printinfo.py
- convert test on printversion from pytest to unittest (see issue #702) 
- updates to docstrings
- add version to a couple of the notebook-styled examples
> Printversion revisions

- docs/content/em/api_FDEM.rst
I typo and small additions/clarifications. `mu` and `varepsilon` are the target of some geophysical applications, so it might be worth to add the 'low-frequency'-bit.
> Typos and small additions

- README.rst
Just noted that the current Zenodo DOI points to version 0.7.1 from January 2018. Zenodo has a cool feature, a DOI for a project that always links to the newest version, and lists all zenodos ever released for that piece of work. For SimPEG, it is [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.596373.svg)](https://doi.org/10.5281/zenodo.596373)
Edit: Corrected Zenodo
> Fix Zenodo DOI

- .travis.yml
- SimPEG/DataMisfit.py
- SimPEG/Directives.py
- SimPEG/Survey.py
- SimPEG/Utils/PlotUtils.py
- examples/07-fdem/plot_loop_loop_2Dinversion.py
- tests/base/test_DataMisfit.py
Fix for Issue #746
- fixed `DataMisfit.std` that now take into consideration `survey.std`. So you are not forced to set `DataMisfit.W` manually anymore
-  Fixed: `Survey.MakeSyntheticData`, if not given a `std`, was overwriting `survey.std` even if already set.  Now it will use `survey.std` if not given a `std` argument.
Explanation:
`DataMisfit.std` was set to 5% by default, but to change it to `survey.std`, it expected a `None` value, thus it never gets updated...
- bonus: light improvement again of `Plot2DData` (reordering of `if` statement so specifying `contourOpts['vmin','vmax']`  without a `clim` works.
- bonus: Somehow PR #725 did not make it to improve `plot_misfit_curves` so I put it back here. Mainly, more option to plot $\phi_m$ or $\phi_small$  and $\phi_smooth$ …
> fix std in DataMisfit and possible bug in PlotUtils

- .travis.yml
- docs/content/basic/installing.rst
- soft removal of python 2.7: we don't explicitly break compatibility as in #731, but it is no longer tested on Python 2.7
- added a note in the docs saying we will not be working to ensure compatibility with python 2.7 anymore
> remove testing on python 2.7 from SimPEG

- SimPEG/EM/Static/DC/RxDC.py
turn IntTrapezoidal into a function that can be reused by both pole and dipole classes rather than duplicating code. 
@micmitch: would you mind taking a quick look at this pr? 
If you take a look at the code 
and please leave any comments or questions here
Thanks!
> light refactor in DC receivers

- .mailmap
This `.mailmap` takes the output of `git shortlog -sne` from the one on the left to the one on the right:
It makes it easier to get clean author info from the various git log commands.  If anyone in the team prefers a different canonical name or email, it's easy to fix that now by updating this file. 
The [sympy wiki entry](https://github.com/sympy/sympy/wiki/Using-.mailmap) mentioned in the file has a ton more details about this, including links to scripts they use to carefully manage theirs.
> Add a .mailmap file to help organize author statistics.

- SimPEG/electromagnetics/static/utils/StaticUtils.py
Related to issue #842 
- Use built-in function for TreeMesh boundary cells 
- Speed up the `closestPointGrid` function
> Fix drapeTopoLoc

- SimPEG/EM/Analytics/FDEM.py
There is no specific reference given, so maybe it means another Ward and Hohmann paper. However, if the Ward and Hohmann of the green SEG-EM-book is meant, then I think there are two errors in the figure.
1. ~There is no **Figure 4.56** in Ward and Hohmann, 1988, SEG; I think it tries to reproduce **Figure 4.2** instead.~ With 4.56 was apparently the equation meant, but it is not specified. So 4.56 is the equation, 4.2 the corresponding figure. I adjusted that.
2. The resistivity in Ward and Hohmann is 100 Ohm.m, but in the example 1000 Ohm.m is used (0.001 S/m), so the result is not exactly the same as in Ward and Hohmann.
This PR fixes these two issues.
If I am wrong and another Ward and Hohmann paper is meant then the correct reference should be added.
> Fix Ward and Hohmann example

- docs/content/basic/getting_started_developers.rst
- docs/content/basic/installing.rst
- docs/content/basic/practices.rst
- docs/content/release/0.14.0-notes.rst
Some of the internal documentation links were pointing to html address instead of internal addresses
> Replace html links to documentation with local links

- SimPEG/directives.py
- SimPEG/fields.py
- SimPEG/flow/richards/simulation.py
- SimPEG/inversion.py
- SimPEG/optimization.py
- SimPEG/survey.py
- SimPEG/utils/counter_utils.py
- SimPEG/utils/model_builder.py
- SimPEG/utils/solver_utils.py
I came across these easy-to-fix stuff when I was reading simpeg code, so decided to submit a short PR before I forgot.
* Minor typo fixes
* Use `isinstance` for type checking (for those who's interested, this [SO answer](https://stackoverflow.com/a/1549854) goes into more detail on `type` vs . `isinstance`). My linter was yelling at me so I obliged. :)
* Double backquote (as opposed to single) for [sphinx inline code formatting](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#inline-markup)
> Typo cleanup & use isinstance for type checks

- SimPEG/utils/solver_utils.py
- tests/utils/test_solverwrap.py
This should allow us to set some default kwargs for certain systems by only accepting them if they are valid to the function, and throwing a warning for invalid kwargs.
> Allows logic to cull unused kwargs from inputs to a function

- tutorials/04-magnetics/plot_2a_magnetics_induced.py
Here is a minor change: np.savetxt() cannot write the inclination, declination and strength of magnetic data, using the SimPEG utils instead.
> change the way of exporting magnetic data

- docs/conf.py
- requirements_dev.txt
I think it would be good to show memory consumption in the examples. This way users will know what is expected, and if a certain example didn't run because of the limitations of their machine. The change makes that in addition to the runtime (blue) it also shows memory (red):
As a response to https://simpeg.discourse.group/t/run-the-example-heagy-et-al-2017-casing-example/138 (btw that discourse thread is still open @lheagy , I don't know what the issue is).
> Show memory usage in examples

- SimPEG/electromagnetics/natural_source/sources.py
- SimPEG/electromagnetics/natural_source/survey.py
- deprecate `AnalyticPlanewave1D` and `Planewave_xy_1DhomotD` in favour of `Planewave1D` (which is currently a pass through that only tracks frequency)
- remove code that duplicated the base FDEM survey behaviour from the `Survey1D` for the MT code
> reduce duplication in the 1D source definitions

- SimPEG/electromagnetics/static/induced_polarization/simulation.py
I believe this fixes the issue posted by @rolandhill about the IP simulation in #955 
two things: 
- there were a `if f is None` call missing, resulting in indexing a None.
- It is preferable to use the mapping to set the size I believe, as `self.model` could be None (which happened in @rolandhill case)
Note: This PR is close to what I fixed for Mag in #958.
> Fix IP simulation when model or field is None

- SimPEG/electromagnetics/static/utils/static_utils.py
Importing from `numpy.matlib` is deprecated since NumPy 1.19.0. This PR replaces the `np.matlib.repmat` by `np.tile`, as outlined here https://numpy.org/doc/stable/user/numpy-for-matlab-users.html
> Replace np.matlib.repmat by np.tile

- SimPEG/electromagnetics/analytics/NSEM.py
- SimPEG/electromagnetics/viscous_remanent_magnetization/simulation.py
Done in two distinct ways:
- Replace `np.matrix(x)` by `np.array(x)` where it is obvious that `x` is at least 2D.
- Replace `np.matrix(x)` by `np.atleast_2d(x)` where this is not the case.
This approach will fail if there is any place where the string annotation has been used:
```
np.matrix('1 2; 3 4')
```
I have not seen it though, so fingers crossed. The tests will show.
Also, matrix multiplication and matrix power might be different, which might require further adjustments. Again, the tests will show.
> Replace np.matrix by regular ndarrays

- tutorials/03-gravity/plot_1a_gravity_anomaly.py
- tutorials/03-gravity/plot_inv_1a_gravity_anomaly.py
- tutorials/03-gravity/plot_inv_1b_gravity_anomaly_irls.py
I noticed a question, "why the gravity signals look "inconsistent" with density values in visualization?", has been asked multiple times, so added notes to the gravity examples to clarify it.
> Add notes to gravity examples

- SimPEG/electromagnetics/utils/current_utils.py
These four lines are "dead code", as they are overwritten later on.
The alternative of removing them would be to add a `return sx, sy, sz` at the end of the removed lines. However, this if-statement is only ever called if two points are identical (`lx=ly=lz=0`), so should very rarely be the case. Additionally, the speed-gain is probably negligible.
> Remove dead code

- SimPEG/utils/io_utils/io_utils_electromagnetics.py
When loading a DCIP3D or DCIP octree survey files, the code will skip the first line if the data_type flag is not volts. When loading secondary potential of apparent chargeability data, SimPEG assumes the data file has the flag IPTYPE=1,2 (which is not necessary to model IP data when forward modeling with GIF codes).
The IO has been updated to skip the survey line if and only if it finds a line that begins with IPTYPE. This should be a more robust function for the IO.
> Fix bug in IO for DCIP3D data

- examples/10-pgi/plot_inv_1_PGI_Linear_1D_joint_WithRelationships.py
- tutorials/13-pgi/plot_inv_1_joint_pf_pgi_full_info_tutorial.py
- tutorials/13-pgi/plot_inv_2_joint_pf_pgi_no_info_tutorial.py
The tutorial were still running smoothly but they actually now account volume twice. Final Alphas are still different than before because volume and normalization are done in a different order since 0.15.2.
> Fix pgi tutorials accounting volume twice

- SimPEG/potential_fields/base.py
- SimPEG/potential_fields/gravity/__init__.py
- SimPEG/potential_fields/gravity/simulation.py
- SimPEG/potential_fields/magnetics/__init__.py
- SimPEG/potential_fields/magnetics/simulation.py
- tests/pf/test_pf_quadtree_inversion_linear.py
As the name says. Make a separate simulation class for the equivalent source layer. This functionality is much more up front as opposed to modifying things after instantiating a Simulation3DIntegral
> Add separate pf quadtree equivalent source simulation

- SimPEG/electromagnetics/time_domain/sources.py
- tests/em/tdem/test_TDEM_crosscheck.py
Bug fixes in the MMR solution for the TDEM h-field problem with a line source. 
- note that `e = - \grad \phi` (hence the sign update)
- the volume term needs to be accounted for in the divergence
Todo:
> TDEM line current h-field update 

- SimPEG/electromagnetics/base_1d.py
- SimPEG/electromagnetics/frequency_domain/simulation_1d.py
- SimPEG/electromagnetics/frequency_domain/sources.py
- SimPEG/electromagnetics/time_domain/sources.py
- tests/em/em1d/test_EM1D_FD_fwd.py
- tests/em/em1d/test_EM1D_FD_jac_layers.py
- tests/em/em1d/test_EM1D_TD_general_fwd.py
- tests/em/em1d/test_EM1D_TD_general_jac_layers.py
Before the next release, this removes the standalone `LineCurrent1D` class in favor of the `LineCurrent` class which was already present.
> Remove LineCurrent1D

- SimPEG/electromagnetics/time_domain/sources.py
- examples/06-tdem/plot_fwd_tdem_waveforms.py
- tests/em/tdem/test_TDEM_sources.py
This PR adds a flexible exponential growth followed by a linear ramp waveform: `ExponentialWaveform`
- parameters: `start_time`, `ramp_on_tau`, `peak_time`, `off_time`
- `eval`, `eval_deriv`, `time_nodes` are implemented
- the gallery example is updated
> TDEM exponential waveform

- SimPEG/regularization/pgi.py
- examples/10-pgi/plot_inv_0_PGI_Linear_1D.py
- tests/base/test_pgi_regularization.py
- small bug where `alpha_pgi` was not taken into account in the definition
- removed unused `alpha_s` argument
- the setter needed to be reworked; use `validate_float` instead (if `None` was passed, which was the default, then we ended up with `None` as multiplier)
- fix example that called alpha_s instead of alpha_pgi
> fix alpha multipliers in `PGI`

- SimPEG/electromagnetics/static/resistivity/fields_2d.py
- tests/em/static/test_DC_2D_analytic.py
Takes the boundary condition into account when calculating the `e` and `j` fields for 2D cell_centered dc resistivity.
address #1033.
> Fix for 2D_CC boundary conditions

- Makefile
- azure-pipelines.yml
Create new `flake-permissive` target in Makefile. The new target runs `flake8`
checking if only a selection of rules are being violated. It's being added with
the intention of start catching `flake8` rules that have already been solved
throughout the entire SimPEG. This new rule should be temporary until every
`flake8` rule has been solved. Make Azure to run two `flake8` checks: the
`flake-permissive` target (that checks only of a selection of flake rules) and
the `flake` target but allowing it to fail (it returns exit code zero even if
some rules are being violated).
> Run flake8 in CI against a selection of rules

- SimPEG/potential_fields/base.py
- SimPEG/potential_fields/gravity/simulation.py
- tests/pf/test_pf_quadtree_inversion_linear.py
As described in https://simpeg.slack.com/archives/CFJUKBPDZ/p1670976419407039 equivalent source models currently do not allow use of inactive cells. The code requires the `cell_z_top` and `cell_z_bottom` to be the same size as `mesh.nC`. Simply changing this to the internally-set `self.nC` allows use of inactive and active cells with the existing `ind_active` parameter.
This change is backwards compatible since using the full active set of cells is always going to be the same as `mesh.nC`, and `self.nC==mesh.nC` in that case.
> Enable use of inactive cells in equivalent source models

- SimPEG/electromagnetics/static/resistivity/simulation.py
- SimPEG/electromagnetics/static/resistivity/simulation_2d.py
- tests/em/static/test_DC_Boundaries.py
Adds an option for the user to explicitly specify which boundary faces are considered to be surface boundaries (that will get a Neumann boundary).
Also fixes a small bug identified by the new tests regarding which boundaries were considered to be Robin boundaries for Tensor and Curvilinear meshes in the previous logic.
> Flexible dc boundary

- SimPEG/potential_fields/base.py
- tests/pf/test_forward_Grav_Linear.py
- tests/pf/test_forward_Mag_Linear.py
- tests/pf/test_grav_inversion_linear.py
- tests/pf/test_mag_inversion_linear.py
- tests/pf/test_mag_inversion_linear_Octree.py
Change default to not use multiprocessing. Was causing too many issues on unsuspecting Windows users.
Also added a note on using the class with n_processes not equal to 1 to warn the users about how to use it when multiprocessing is enabled.
> Change default n_processes for potential fields

- SimPEG/electromagnetics/static/resistivity/simulation_1d.py
Storing reals as complex lead to a tanh overflow... also save a lot of time not computing tanh on complex values.
At some point in the future, the 1D DC resistivity simulator should be brought up to the same level as the 1D em functionality.
> Do not store real lambdas as complex

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/post-install.yml
This adds Issue templates using fillable forms. It is modeled after the forms numpy uses for their issues.
These are (mostly complete) starting points, if there's anything else I missed though let me know.
For approximate look at what the forms will look like, check them out here: https://github.com/jcapriot/simpeg/tree/issue_forms/.github/ISSUE_TEMPLATE
> Add issue forms for github

- SimPEG/electromagnetics/static/resistivity/receivers.py
- SimPEG/electromagnetics/static/resistivity/simulation_1d.py
- tests/em/static/test_DC_1D_jvecjtvecadj.py
- tutorials/05-dcr/plot_fwd_1_dcr_sounding.py
- tutorials/05-dcr/plot_inv_1_dcr_sounding.py
- tutorials/05-dcr/plot_inv_1_dcr_sounding_irls.py
- tutorials/05-dcr/plot_inv_1_dcr_sounding_parametric.py
Took the time this morning to just update the DC1D to be more flexible for receivers and sources.
It now supports `Pole` and `Dipole` receivers, `Pole`, `Dipole`, `Multipole` sources, and arbitrary combinations of these.
It also overhauled the class to use faster forward and jacobian kernels, while making use of the splined output for the hankel transform, resulting in far fewer calls to those faster kernel functions.
It's calling structure has been overhauled to match the 2D and 3D simulations, (i.e. no setting `data_type` on the simulation, it should be set on the receivers).
There was also a small bug setting repeated geometric factors on receivers that was caught here too.
> Update DC1D for flexibility and speed

- SimPEG/regularization/pgi.py
Fix the checks for the `reference_model` attribute in the `PGIsmallness` regularization class. Replace the old `"mref"` for `"reference_model"`.
> Fix check for reference_model in PGI regularization

- SimPEG/regularization/jtv.py
- tests/base/test_jtv.py
Updating the `JointTotalVariation` to work for more than 2 models as the formulation is generalizable to the number of physical property models.
> update JTV to work for an arbitrary number of models

- SimPEG/electromagnetics/viscous_remanent_magnetization/sources.py
- SimPEG/flow/richards/survey.py
- SimPEG/utils/drivers/gravity_driver.py
- SimPEG/utils/drivers/magnetics_driver.py
- SimPEG/utils/io_utils/io_utils_general.py
- examples/20-published/plot_heagyetal2017_casing.py
- examples/20-published/plot_schenkel_morrison_casing.py
- tests/em/nsem/inversion/test_BC_Sims.py
Hi! According to numpy/numpy#14882, **_np.{builtin}_**(np.float, np.str, etc.), which were aliases to python builtin types, was deprecated, and has been removed in numpy 1.24.
It replaces numpy's type aliases np.{builtin} with corresponding builtin types according to [this note](https://github.com/numpy/numpy/blob/da1621637b7c59c155ec29466fb5f810ebd902ac/doc/release/upcoming_changes/14882.deprecation.rst). It may be better to consider using more precise ones like **np.int64** or **np.complex64**, but it deserves another pr I guess.
Changes are done with regular expressions.
```regex
np\.(bool|int|float|complex|object|str)(?!\d|_|e) -> $1
np\.long(?!\d|_|e) -> int
np\.unicode(?!\d|_|e) -> …
```
> Replace deprecated numpy type aliases with builtin types

- SimPEG/objective_function.py
- SimPEG/regularization/base.py
- SimPEG/regularization/pgi.py
- tests/base/test_objective_function.py
Rewrite the `__add__` method of `BaseObjectiveFunction` so by default it performs the same task for any `ComboObjectiveFunction` or any of its child classes. Add a new `unpack_on_add` attribute to `ComboObjectiveFunction` to decide weather to unpack its objective functions after an addition, or if it should be added as a whole. Set `unpack_on_add=True` by default on `ComboObjectiveFunction`, but set it to `False` for regularization classes, like `WeightedLeastSquares` and `PGI`. Add tests for the new changes.
Fixes an unexpected behaviour when subclassing `ComboObjectiveFunction`: by default its `__add__` method would have worked differently than it does for the parent, adding the …
> Generalize __add__  for any ComboObjectiveFunction

- SimPEG/dask/electromagnetics/static/induced_polarization/simulation.py
- SimPEG/electromagnetics/static/induced_polarization/simulation.py
- tests/dask/test_IP_jvecjtvecadj_dask.py
`fields` needs to be called first to set `_scale` for IP simulation. It is the case without dask by calling `getJ` at the beginning of the `getJtJdiag` function, but not with the dask function `dask_getJtJdiag`.
to a Pull Request 
You can test it by adding `from SimPEG import dask` to the IP tutorial: https://docs.simpeg.xyz/content/tutorials/06-ip/plot_inv_2_dcip2d.html
> Fix IP simulation / inversion with SimPEG.dask

- SimPEG/props.py
- tests/base/test_Props.py
Allow invertible properties to be optional.
Invertible properties were implicitly required to be given a value. They would throw an error if you tried to access them before setting. This adds a flag to `props.Invertible` (and `props.PhysicalProperty`) that allows us to create optional invertible properties.
> conditionally allow invertible property to also be optional

- SimPEG/electromagnetics/time_domain/simulation.py
- tests/em/tdem/test_TDEM_DerivAdjoint.py
- tests/em/tdem/test_TDEM_DerivAdjoint_RawWaveform.py
Fixes a few small testing errors on main.
> Test patches

- SimPEG/potential_fields/gravity/simulation.py
- SimPEG/potential_fields/magnetics/simulation.py
Instead of using gzz = -gxx - gyy, which needs to be adjusted if inside a cell.
Always calculates the gzz component of the potential field tensors using the kernel functions, instead of making the gzz = -gxx - gyy simplification.
The previous method of calculating gzz from gxx and gyy is invalid when the observation point is internal to a cell. In these cases it needs to be adjusted by:
gzz = -gxx - gyy - 4 * pi
Best practice will be to implement `point2index` for each discretize mesh, which will be queried at the start to determine for each observation which (if any) cell they are located in, then use that information to make the correction listed above. In the mean time, we …
> Always calculate gzz if needed

- .flake8
- tutorials/08-tdem/plot_fwd_1_em1dtm_waveforms.py
- tutorials/08-tdem/plot_fwd_2_tem_cyl.py
Remove `W291` and `W293` from list of ignored rules in `.flake8`. Remove
trailing whitespaces and whitespaces in empty lines.
> Fix W291 and W293 flake errors: white spaces

- .flake8
- SimPEG/data.py
- SimPEG/directives/directives.py
- SimPEG/electromagnetics/frequency_domain/receivers.py
- SimPEG/electromagnetics/frequency_domain/sources.py
- SimPEG/electromagnetics/static/resistivity/IODC.py
- SimPEG/electromagnetics/static/resistivity/simulation_2d.py
- SimPEG/electromagnetics/static/utils/static_utils.py
- SimPEG/electromagnetics/time_domain/receivers.py
- SimPEG/electromagnetics/time_domain/sources.py
- SimPEG/electromagnetics/utils/current_utils.py
- SimPEG/maps.py
- SimPEG/regularization/base.py
- SimPEG/regularization/pgi.py
- SimPEG/simulation.py
- SimPEG/survey.py
- SimPEG/utils/code_utils.py
- SimPEG/utils/io_utils/io_utils_electromagnetics.py
- SimPEG/utils/model_utils.py
- SimPEG/utils/pgi_utils.py
- SimPEG/utils/plot_utils.py
- SimPEG/utils/solver_utils.py
Remove B028 from the list of ignored rules in `.flake`. Explicitly set
stacklevel on `warning.warn` calls.
> Fix B028 flake error: non-explicit stacklevel

- SimPEG/potential_fields/gravity/receivers.py
- SimPEG/potential_fields/gravity/simulation.py
- tutorials/03-gravity/plot_1b_gravity_gradiometry.py
Add admonitions to the `Point` receiver for gravity simulations. Fix unit in the plot legend of one of the examples.
The error in the example was caught by @johnweis0480. We concluded that returned gravity units should be explicitly mentioned in the documentation.
> Make units of gravity simulations more explicit

- SimPEG/electromagnetics/natural_source/utils/edi_files_utils.py
Makes the `utm` import optional.
The `utm` package was a hard import, and it was also not listed as a requirement of SimPEG. As this is a very minor package, (and I don't even believe the EDI import is tested at the moment), we should make this an optional package and not a hard dependency.
> Optionally import utm

- SimPEG/dask/potential_fields/base.py
- SimPEG/potential_fields/base.py
- SimPEG/potential_fields/gravity/simulation.py
- SimPEG/potential_fields/magnetics/simulation.py
- tests/meta/test_meta_sim.py
- tests/pf/test_forward_Grav_Linear.py
Allows users to control the type of the stored sensitivity matrix.
In the non-dask version the sensitivity was being stored as a `np.float64` implicitly. This changes it to be in line with the dask version (`np.float32`), but also now allows the user to change the default if they so desire.
> Set storage type of pf sensitivity matrix

- tutorials/03-gravity/plot_inv_1b_gravity_anomaly_irls.py
Modify example that runs a gravity sparse inversion: remove the `BetaSchedule` directive to avoid cooling beta twice. The `Update_IRLS` directive has its own builtin beta scheduling scheme.
> Fix sparse inversion example: remove beta schedule

- SimPEG/directives/directives.py
Small pr to fix a bug in the plotting of tikhonov curves. Since we turn the data misfit into a combo objective function, we need to unpack it to get the number of data  
> unpack the data misfits for plotting tikhonov curves

- docs/Makefile
- docs/content/getting_started/contributing/documentation.rst
Adding a section under documentation under contributing guidelines that explains how to build and serve the docs locally.
> Add building docs and serving them to documentation

- SimPEG/simulation.py
- tests/base/test_maps.py
- tests/em/static/test_DC_2D_jvecjtvecadj.py
- tests/meta/test_meta_sim.py
- tests/pf/test_grav_inversion_linear.py
- tests/pf/test_mag_inversion_linear.py
- tests/pf/test_pf_quadtree_inversion_linear.py
Add a new `random_seed` argument to the `make_synthetic_data` method.
Switch to the Numpy's random number generator object and pass the
`random_seed` argument to `np.random.default_rng`, allowing users to
specify a random seed for the synthetic noise. Set random seeds in some 
tests that were failing due to the new random state that the usage of 
`make_synthetic_data` with `random_seed` created in the test suite.
> Allow to use random seed in make_synthetic_data

- SimPEG/regularization/sparse.py
Fix the message for the deprecation of `gradientType` for `gradient_type` in `SparseSmoothness` regularization.
> Fix deprecation warning for gradientType in SparseSmoothness

- SimPEG/potential_fields/gravity/survey.py
Edits the docstring of `gravity.Survey` to correctly describe the `source_field` argument.
> Fix description of source_field in gravity survey

- SimPEG/regularization/base.py
- tests/base/test_regularization.py
Add a new `weights_keys` method to `BaseRegularization` that exposes the keys of the private `_weights` attribute. Add tests for the new feature.
Fixes #1318
> Add `weights_keys` method to `BaseRegularization`

- .pre-commit-config.yaml
- environment_test.yml
- requirements_dev.txt
- requirements_style.txt
Bump versions of `black`, `flake8` and flake plugins to their latest available versions in PyPI and in conda-forge. Pin versions of `flake8` and its plugins in the `requirements_style.txt`, `environment_test.yml` and `pre-commit` configuration files. This prevents inconsistencies between the Style Checks run in Azure and the ones run locally through `pre-commit` or `make flake`.
> Bump versions of flake8 and black and pin flake plugins

- SimPEG/simulation.py
Move the `__init__`` method in `BaseSimulation` to the top of the class. This just improves readability and shouldn't change the behaviour of the class.
> Move `__init__` in `BaseSimulation` to the top of the class

- SimPEG/regularization/base.py
- SimPEG/regularization/regularization_mesh.py
- SimPEG/utils/mat_utils.py
- tests/base/test_regularization.py
The initial implementation of coterminal angles used an average of cell sizes to determine the cell centered length. Those distances are slightly different (by 88%) than the cell gradient distances used by the `regularization_mesh.cell_gradient_` operators on octree changes. 
* [N/A] Added necessary documentation to any new functions/classes following the
Fixes large gradients computed on the -pi/pi transition, resulting in artifacts in the model.
Current results from `examples\03-magnetics\plot_inv_mag_MVI_Sparse_TreeMesh.py.`:
Title should be L2 Spherical model...
After fix:
> Fix issue with lengthscales in coterminal angle calculations

- SimPEG/objective_function.py
- tests/base/test_objective_function.py
Simplify the check for invalid multipliers in `ComboObjectiveFunction`. Move private methods used for validation of arguments to private functions since they didn't need any other attribute of the class. Add tests for the new checks for invalid multipliers.
> Simplify check for invalid multipliers

- SimPEG/regularization/regularization_mesh.py
`ravel` will avoid returning a new copy of the array; since a new array is already being created w/ toarray this is safe.
Thanks @jedman for  bringing this to my attention.
> Ravel instead of flatten

- SimPEG/utils/mat_utils.py
- tests/base/test_utils.py
Fix the implementation of the `coterminal` function: use the `mod` operator to ensure that the functions returns the correct coterminal angle defined in $[-\pi, \pi)$. Add more tests.
Fixes #1333
---
PR to address issue #1333 , where the sign of coterminal angles is not preserved. Also fixes potential issues with angle > $2 \pi$
Running the example/03-magnetics/plot_inv_mag_MVI_Sparse_TreeMesh
Before
After
> Fix implementation of coterminal function

- SimPEG/regularization/cross_gradient.py
This make the hessian approximation in the cross gradient regularization actually SPD.
The previous approximation was not actually symmetric positive semidefinite. Every once in a while it would result in some odd minimization effects in some of my examples. This actually makes it the approximation guaranteed to be SPD. It now uses the actual $J^T J$ as the approximation (instead of something that I had assumed was $J^T J$. This doesn't change our tutorial results by the way, and outside of a few odd cases shouldn't affect the results very much.
Makes the CG hessian approximation actually SPD
> Update cross gradient hessian approximation

- SimPEG/objective_function.py
- SimPEG/regularization/base.py
- tests/base/test_regularization.py
Assign the parent on the list of  `ComboObjectiveFunction.objfcts`, such that a child function can navigate up the tree and interact with its siblings. 
We could eventually apply the same mechanics to the `BaseObjectiveFunction`, such that the misfits can also have parental relationships, but that's beyond scope.
Closes #1341 
The parent on the objective function was never set, and prevented the Sparse amplitude to apply the `gradient_type = "total"`
> ISSUE-1341: Set parent of objective functions

- SimPEG/regularization/correspondence.py
- SimPEG/regularization/cross_gradient.py
- SimPEG/regularization/jtv.py
Fix LaTeX in second order partial derivatives shown in regularization docstrings. Replace $\frac{\partial \phi^2}{\partial m^2}$ for $\frac{\partial^2 \phi}{\partial m^2}$.
> Fix partial derivatives in regularization docs

- SimPEG/data_misfit.py
- SimPEG/directives/directives.py
- SimPEG/directives/pgi_directives.py
- SimPEG/directives/sim_directives.py
- SimPEG/objective_function.py
- SimPEG/regularization/__init__.py
- SimPEG/regularization/base.py
- SimPEG/regularization/correspondence.py
- SimPEG/regularization/cross_gradient.py
- SimPEG/regularization/jtv.py
- SimPEG/regularization/pgi.py
- SimPEG/regularization/sparse.py
- SimPEG/regularization/vector.py
- examples/20-published/plot_tomo_joint_with_volume.py
- tests/base/test_cross_gradient.py
- tests/base/test_objective_function.py
- tests/base/test_pgi_regularization.py
- tests/em/em1d/test_EM1D_FD_jac_layers.py
- tests/pf/test_pf_quadtree_inversion_linear.py
- tests/utils/test_mat_utils.py
Remove the factor of 1/2 in front of data misfit and regularization terms. This has caused many headaches as outlined in #763. 
One important note:
- the Joint Total Variation never had a 1/2 in front. The documentation and the implementation did not match each other (the documentation stated there was a factor of 1/2, but in the code, there wasn't). So this will change _will_ require that scaling factors used in front of the joint total variation regularization be multiplied by a factor of 2 to obtain the same result if a fixed value was used (cc @jcapriot: I would appreciate a double-check from you on this if you don't mind!)  
This will close #763 
- remove the factor of 1/2 …
> Remove factor of half in data misfits and regularizations

- tests/pf/test_forward_Grav_Linear.py
Remove some unneeded lines in gravity simulation tests, particularly the ones that tests warnings and errors being raised. Replace `unittest.mock.patch` with `pytest`'s Monkeypatch to fake `choclo` not being installed.
> Simplify a few gravity simulation tests

- SimPEG/simulation.py
- tests/base/test_simulation.py
- define the kernel functions at cell nodes rather than at cell centers 
- also move the __init__ from the middle of the class to the top of the class definition
- kernel functions should be defined on nodes as we think of them being piecewise linear (rather than discontinuous as we talk about at cell centers). This makes it more in line with other physical simulations
- this then also introduces techniques for discrete integration (eg Gaussian quadrature) 
- both of these things are important for teaching purposes
> Exponential Sinusoids Simulation

- SimPEG/directives/directives.py
- examples/02-gravity/plot_inv_grav_tiled.py
- examples/_archived/plot_inv_grav_linear.py
- examples/_archived/plot_inv_mag_linear.py
- tests/base/test_directives.py
- tests/dask/test_grav_inversion_linear.py
- tests/dask/test_mag_MVI_Octree.py
- tests/pf/test_mag_MVI_Octree.py
- tests/pf/test_mag_inversion_linear.py
- tests/pf/test_mag_vector_amplitude.py
- tutorials/02-linear_inversion/plot_inv_2_inversion_irls.py
- tutorials/03-gravity/plot_inv_1a_gravity_anomaly.py
- tutorials/03-gravity/plot_inv_1b_gravity_anomaly_irls.py
- tutorials/04-magnetics/plot_inv_2a_magnetics_induced.py
- tutorials/06-ip/plot_inv_2_dcip2d.py
- tutorials/06-ip/plot_inv_3_dcip3d.py
- tutorials/13-joint_inversion/plot_inv_3_cross_gradient_pf.py
Remove the `everyIter`, `threshold` and `normalization` properties of `UpdateSensitivityWeights`. Add tests to check if errors are being raised after passing removed arguments to its constructor. Update tests and examples using the removed arguments and properties.
Part of the solution for https://github.com/simpeg/simpeg/issues/1302
> Removed deprecated properties of UpdateSensitivityWeights

- SimPEG/directives/directives.py
- SimPEG/directives/sim_directives.py
- tests/base/test_directives.py
Remove the `debug` argument and property from `InversionDirective`, add new test to check if it raises an error when passing it as argument. Update directive class using the `debug` property.
Part of the solution for https://github.com/simpeg/simpeg/issues/1302
Most of these changes were cherry-picked from https://github.com/simpeg/simpeg/pull/1306
> Remove the debug argument from InversionDirective

- SimPEG/regularization/regularization_mesh.py
- tests/base/test_regularization.py
Remove the `cellDiffx`, `cellDiffy`, and `cellDiffz` properties of
`RegularizationMesh`.
Part of the solution for #1302
> Remove cellDiff properties of RegularizationMesh

- docs/_templates/autosummary/attribute.rst
- docs/_templates/autosummary/base.rst
- docs/_templates/autosummary/method.rst
- docs/conf.py
Stops the left sidebar from being completely expandable for every single item in the documentation.
https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/navigation.html#remove-reveal-buttons-for-sidebar-items
No number... but the docs take so long to build now....
Faster doc building (excluding the examples and tutorials)
[](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/performance.html)
> Speed up sphinx documentation building

- SimPEG/potential_fields/magnetics/simulation.py
- tests/pf/test_forward_Mag_Linear.py
Remove the deprecated `modelType` property in the magnetic simulation and add test function checking that error is raised when trying to access it.
Part of the solution to #1302
> Remove deprecated modelType in mag simulation

- docs/content/release/0.21.0-notes.rst
- docs/content/release/index.rst
Add release notes for SimPEG v0.21.0 to the docs.
> Add release notes for SimPEG v0.21

- SimPEG/potential_fields/magnetics/sources.py
Remove the old `parameters` argument from the docstrings of the `UniformBackgroundField` class.
> Remove the parameters argument from docstring

- .github/workflows/pull_request.yml
Updates permissions for reviewdog actions.
Looks like it explicitly needs to be given read permissions for the contents, and write permissions for the pull-requests to modify PR's from public forks.
> Safely run reviewdog on `pull_request_target` events

- simpeg/meta/multiprocessing.py
Join's the multiprocessing queues in the `MultiprocessingMetaSimulation` when the simulation is joined.
Likely caused the broken pipe errors in the testing environment.
> Ensure the queue's are joined when the meta simulation is joined.

- simpeg/directives/directives.py
- tests/base/test_directives.py
Fix bug in the constructor of beta estimator directive classes: the `seed` argument was being passed as a positional argument to the parent's constructor, which would assign it to the `n_pw_iter` attribute instead to the `seed`, leading to unwanted behaviours. Pass the arguments to the constructor through keywords to make it more explicit and less prone to errors. Add tests that would fail without this bugfix. Remove the `n_pw_iter` and the `method` arguments from the constructor of `BaseBetaEstimator`.
Related to #1290
> Fix bug on arguments of beta estimator directives

- simpeg/utils/pgi_utils.py
- tests/utils/test_gmm_utils.py
Update call of `_print_verbose_msg_init_end` in `GaussianMixtureWithPrior`: since `scikit-learn>=1.5.0` it requires two positional arguments. Use a `try-except` block to maintain support for older versions of `scikit-learn`. Create a new private method for the `GaussianMixtureWithPrior` class to wrap the `_print_verbose_msg_init_end` method including the `try-except` block. Add tests.
Fix #1475
> Fix call to private method in GaussianMixtureWithPrior

- azure-pipelines.yml
Fix issues in the new (experimental) scripts for deployment of docs to `simpeg-doctest`. Fetch the `gh-pages` before trying to checkout it. This is needed because we clone the repo with `--depth 1`. When passing this option, git appends the `--single-branch` option meaning the `dev` branch is the only branch that is being cloned. Improve how we clone the `simpeg-doctest` repo: clone quietly to reduce output lines, and specify the branch while deploying release docs (in case the default branch in the repo gets changed).
> Fix script for new deployment of docs

- simpeg/maps.py
- tests/base/test_maps.py
Add `random_seed` argument to `IdentityMap.test`. Add a new `random_seed` argument to the `test` method of `IdentityMap` to control the random state for creating the `m` array if it's not provided. Update tests to use the `random_seed`. If the `m` array is passed while running the `test()` method, specify the keyword for the argument to avoid relying only on its position.
**TODO:**
> Add `random_seed` to the `test` method of maps

- tutorials/03-gravity/plot_1a_gravity_anomaly.py
Correcting contour colors in User Guide: Gravity: plot 1a
**Squash and Merge Summary**
Correcting contour colors in a gravity plot in the User Guide for a gravity plot: correctly use the color limits both in the contours and while building the custom color bar.
In the last figure of the User Guide: Gravity: plot 1a, the plotted contour colors do not correspond to the correct gravity anomaly value indicated in the colorbar on the right.
Relevant section:
https://docs.simpeg.xyz/content/tutorials/03-gravity/plot_1a_gravity_anomaly.html#simulation-gravity-anomaly-data-on-tensor-mesh
There appears to me a mismatch between the plotted contour colors of gravity anomaly and the colorbar on the right.
Currently, the figure displays like this:
However it should plot like this:
The mismatch can be …
> Fix contour colors in gravity plot in User Guide

- docs/conf.py
Configure Sphinx autodoc to hide type hints from signatures of functions, methods and classes to improve readability. Expected types for each parameter should be listed in the docstring.
> Hide type hints from signatures in documentation pages

- .github/ISSUE_TEMPLATE/release-checklist.md
- docs/_static/versions.json
- docs/conf.py
Configure the version warning banner in Sphinx PyData theme. Set v0.22.0 as the preferred version in `versions.json`. Remove leading `v` in version numbers in `versions.json`. Remove leading `v` in the `switcher_version` variable defined in `docs/conf.py`.
> Configure version warning banner in Sphinx

- simpeg/electromagnetics/natural_source/utils/plot_data_types.py
Make them less prone to failing by splitting the imports, so we don't rely on matplotib importing numpy in its base `__init__.py`.
Fixes #1502
> Improve imports in natural source utils

- .ci/azure/pypi.yml
Configure the deploy job in the PyPI stage on Azure to only trigger after a release or a nightly run. This prevents trying to push the same release to TestPyPI multiple times.
> Deploy to TestPyPI only on nightly builds

- simpeg/electromagnetics/natural_source/receivers.py
- simpeg/electromagnetics/natural_source/simulation_1d.py
- simpeg/electromagnetics/natural_source/survey.py
- simpeg/electromagnetics/natural_source/utils/plot_utils.py
- simpeg/utils/code_utils.py
- tests/em/nsem/forward/test_Problem1D_AnalyticVsNumeric.py
- tests/em/nsem/forward/test_Simulation3D_vs_Analytic_pytest.py
- tests/em/nsem/inversion/test_NSEM_3D_jvecjtvecadj_pytest.py
- tests/em/nsem/survey/test_nsem_data.py
Suggestions for #1454
Restructures the classes and fixes several errors.
There's a bit here that I am suggesting to change.
First some errors that were in the original PR:
* Removes unused `return_complex` argument that was defined on the constructors in favor of passing `complex` to the component argument (Throws an error `eval_deriv` if `component=='complex'`).
* Restructures the inheritance using a new base class:
* New base `BaseNaturalSourceRx`
* handles setting location pairs and ensuring they're matching pairs (both array_like, with the same shape).
* significantly simplifies the `getP` method (instead of referring to each location array by a name, it passes the requested index).
* Ensures `nD` is properly described.
* Classes no longer inherit from the `ApparentConductivity` class …
> 1454 suggestions

- simpeg/utils/pgi_utils.py
Fix typo and update ASCII style of a comment block in `pgi_utils.py`.
Small non-controversial take-out from https://github.com/simpeg/simpeg/pull/1075
@simpeg/simpeg-developers - ready for review
> Minor fixes to disclaimer in `pgi_utils.py`

- simpeg/utils/code_utils.py
Use the `discretize`'s `requires` to decorate `mem_profile_class`, instead of `simpeg.utils.code_utils.requires`, since the former is intended to be used for modules, while the latter should be used for attributes.
I completely missed in #1104 , that
- `simpeg.utils.code_utils.requires` for attributes is, and not like
- `discretize.utils.code_utils.requires` for modules.
Fixing this by using the discretize version for the `mem_profile_class` function.
@simpeg/simpeg-developers - ready for review
> Fix misuse of the `requires` decorator in `code_utils.py`

- simpeg/fields.py
- simpeg/potential_fields/magnetics/sources.py
Replace `SimPEG` for `simpeg` in a few missing docstrings, so Sphinx can link them to the respective classes and functions.
> Use lowercase simpeg in a few missing docstrings

- .ci/environment_test.yml
- environment.yml
- pyproject.toml
- simpeg/electromagnetics/static/resistivity/IODC.py
- simpeg/utils/code_utils.py
- simpeg/utils/pgi_utils.py
- tests/utils/test_report.py
Set `sklearn` and `pandas` as optional dependencies in `pyproject.toml`. Make use of `discretize`'s `requires` utils function to decorate the functions and methods that require either `pandas` or `scikit-learn` to be installed, specifically in `simpeg.electromagnetics.static.resisitivity.IO` and PGI-related classes.
`sklearn` and `pandas` are comparably heavy dependency, but they are only used in one specific place each:
- `pandas`: `simpeg/electromagnetics/static/resistivity/IODC.py`;
- `sklearn`: `simpeg/utils/pgi_utils.py`.
As such, they are potentially only used by a fraction of the SimPEG users.
This PR implements them as soft dependencies, in the same way as `matplotlib` is a soft dependency in `discretize`.
expect [style](https://docs.simpeg.xyz/content/getting_started/practices.htm …
> Make `pandas` & `scikit-learn` optional dependencies

- simpeg/utils/code_utils.py
- tests/base/test_validators.py
The current implementation of `simpeg.utils.code_utils.validate_ndarray_with_shape` works for numbers or lists, but fails for `np.ndarray`'s.
Example
```python
import numpy as np
from simpeg.utils.code_utils import validate_ndarray_with_shape
``` 
First a list, all as expected, it returns a complex numpy array.
```python
validate_ndarray_with_shape('Test 1', [1+1j, 2+2j], '*', (float, complex))
```
```
array([1.+1.j, 2.+2.j])
```
Now directly for a complex  numpy array: It casts the array to the first provided dtypes, here floats, and raises a warning if that casting has some side-effects, here that it casts complex values to real values. Not what was wanted.
```python
validate_ndarray_with_shape('Test 1', np.array([1+1j, 2+2j]), '*', (float, complex))
```
``` …
```
> Fix validate_ndarray_with_shape

- simpeg/utils/pgi_utils.py
- tests/base/regularizations/test_pgi_regularization.py
Fix bug while checking range of 2d weights. Use Numpy's `a.any()` method instead of Python built-in `any()` function to check if the `weights` is within the `[0, 1]` range. The `any()` function doesn't work with 2d arrays of bools. Convert weights to array before checking shape to allow array-like `weights`. Update method's docstring. Add tests that catch the bug. Include more tests for the `_check_weights` method to extend coverage and cover different scenarios.
Fixes bug reported in https://simpeg.discourse.group/t/error-in-inversion-algorithm-for-pgi-inversion-when-setting-gmm-update-true/603
> Fix bug in GMM's `_check_weights`

- docs/_static/versions.json
- docs/content/release/0.22.2-notes.rst
- docs/content/release/index.rst
Bring in the release notes of `v0.22.2` from the `maintenance/v0.22.x` branch. Add `v0.22.2` to `versions.json`.
> Add release notes after v0.22.2

- simpeg/potential_fields/base.py
- simpeg/potential_fields/gravity/simulation.py
- simpeg/potential_fields/magnetics/simulation.py
Apply a minor fix to the deprecation notice of `ind_active` in the potential field simulations.
> Minor fix in deprecation notice in docstrings

- examples/04-dcip/plot_inv_dcip_dipoledipole_3Dinversion_twospheres.py
- examples/06-tdem/plot_inv_tdem_1D.py
- examples/06-tdem/plot_inv_tdem_1D_raw_waveform.py
- examples/20-published/plot_booky_1D_time_freq_inv.py
- examples/20-published/plot_booky_1Dstitched_resolve_inv.py
- examples/20-published/plot_heagyetal2017_casing.py
- examples/20-published/plot_heagyetal2017_cyl_inversions.py
- examples/_archived/plot_inv_dcip_dipoledipole_2_5Dinversion_irls.py
- simpeg/electromagnetics/natural_source/utils/test_utils.py
- simpeg/electromagnetics/static/spectral_induced_polarization/run.py
- simpeg/maps/_injection.py
- simpeg/maps/_parametric.py
- tests/base/regularizations/test_regularization.py
- tests/base/test_maps.py
- tests/em/nsem/inversion/test_complex_resistivity.py
- tutorials/01-models_mapping/plot_1_tensor_models.py
- tutorials/01-models_mapping/plot_2_cyl_models.py
- tutorials/01-models_mapping/plot_3_tree_models.py
Deprecate the `indActive`, `actInd` arguments and properties from maps and replace them for `active_cells`. Deprecate the `valInactive` argument and property from `InjectActiveCells` and replace it for `value_inactive`. Add tests for the deprecations. Avoid a try and except pattern in the setter for `value_inactive`: we don't want to ignore any error that might happen in those lines. Update usage of `actInd`, `indActive` and `valInactive` in tutorials and examples.
Part of #1121
> Replace `indActive` and `actInd` for `active_cells` in maps

- tests/base/test_maps.py
- tests/em/vrm/test_vrmfwd.py
- tests/pf/test_base_pf_simulation.py
Extend tests for some of the latest deprecated arguments to ensure that after passing the deprecated argument to the class constructor not only we receive the right warning, but the class still behaves in the same way it will if passing the new argument.
> Test assigned values when passing deprecated args

- tests/base/test_data_misfit.py
- tests/base/test_directives.py
- tests/base/test_joint.py
- tests/dask/test_DC_jvecjtvecadj_dask.py
- tests/dask/test_IP_jvecjtvecadj_dask.py
- tests/dask/test_grav_inversion_linear.py
- tests/dask/test_mag_MVI_Octree.py
- tests/dask/test_mag_inversion_linear_Octree.py
- tests/em/static/test_DC_2D_jvecjtvecadj.py
- tests/em/static/test_DC_Utils.py
- tests/em/static/test_DC_jvecjtvecadj.py
- tests/em/static/test_IP_2D_jvecjtvecadj.py
- tests/em/static/test_IP_jvecjtvecadj.py
- tests/em/static/test_SIP_2D_jvecjtvecadj.py
- tests/em/static/test_SIP_jvecjtvecadj.py
- tests/em/static/test_SPjvecjtvecadj.py
- tests/em/vrm/test_vrminv.py
- tests/utils/test_mat_utils.py
Pass a `random_seed` when calling `make_synthetic_data` method of simulations in tests so we ensure that they are always run with the same synthetic data. Remove unused calls to `np.random.seed`.
> Use random seed when using `make_synthetic_data` in tests

- examples/05-fdem/plot_inv_fdem_loop_loop_2Dinversion.py
- examples/20-published/plot_heagyetal2017_cyl_inversions.py
- examples/20-published/plot_laguna_del_maule_inversion.py
- simpeg/directives/directives.py
- simpeg/directives/sim_directives.py
- simpeg/utils/mat_utils.py
- tests/base/test_directives.py
- tests/utils/test_mat_utils.py
Replace `seed` for `random_seed` in directive classes. Replace the `seed` argument for a new `random_seed` argument in `eigenvalue_by_power_iteration`. Update usage of `seed` argument in tests and in codebase. Add tests to check the deprecations.
Part of #1461
> Replace `seed` for `random_seed` in directives

- simpeg/electromagnetics/static/resistivity/survey.py
- simpeg/electromagnetics/static/spectral_induced_polarization/run.py
- simpeg/electromagnetics/static/utils/static_utils.py
- tests/em/static/test_dc_survey.py
- tests/em/static/test_spectral_ip_mappings.py
- tests/em/static/test_static_utils.py
Replace `ind_active` for `active_cells` in `drapeTopotoLoc`, `drape_electrodes_on_topography` and `spectral_ip_mappings`. Test warnings and errors for the deprecations. Update usage of `active_cells`.
Closes #1121
> Replace old args for `active_cells` in EM static functions

- simpeg/potential_fields/_numba_utils.py
- simpeg/potential_fields/magnetics/_numba_functions.py
- simpeg/potential_fields/magnetics/simulation.py
- tests/pf/test_equivalent_sources.py
Implement magnetic equivalent sources using Choclo as the engine. Allow magnetic equivalent sources to take ``engine="choclo"``. Implement new Numba-based forward and sensitivity matrix functions that use Choclo's forward modelling functions for a prism. These new functions can take a 2D mesh and the arrays for the top and bottom boundaries for each cell and compute the forward or build the sensitivity matrix by iterating over each prism in the layer. Add extended tests for the new implementation that also extend the tests for the geoana-based implementation.
Closes #1373
TODO:
> Implement magnetic eq sources with Choclo

- .ci/environment_test.yml
- environment.yml
- pyproject.toml
- simpeg/electromagnetics/frequency_domain/sources.py
- simpeg/electromagnetics/time_domain/sources.py
Updates for geoana 0.7.
>
0.7 geoana will no assume zero at singularities, instead filling with `np.nan`. Now we must explicitly remove any potential singular points after evaluations.
As of right now these look to be the only failure points due to the most recent `geoana`.
> Fixes for most recent geoana 0.7

- simpeg/regularization/_gradient.py
Fix RST syntax to properly show the math and the examples in the docstring of the regularization class. Solves some typos and improve how the math symbols and arguments are displayed.
> Fix docstring of ``SmoothnessFullGradient``

- simpeg/utils/mat_utils.py
Fix RST syntax to show math in the `eigenvalue_by_power_iteration` function.
> Fix math in docstring of eigenvalue_by_power_iteration

- simpeg/potential_fields/magnetics/simulation.py
- simpeg/simulation.py
- simpeg/utils/solver_utils.py
- tests/utils/test_default_solver.py
Add a `warn=False` argument to the `get_default_solver()` function. Only when `warn=True`, the warning about the setting of the default solver is raised. This makes the function not to raise a warning when called with the default arguments. When default solvers are being used within simulations, call the function with `warn=True` to let users know about the solver being automatically selected. Update tests accordingly.
Fix #1563
> Only warn about default solver when set in simulations

- .ci/environment_test.yml
- environment.yml
- pyproject.toml
- simpeg/electromagnetics/base_1d.py
- simpeg/electromagnetics/static/resistivity/simulation_1d.py
- simpeg/electromagnetics/time_domain/simulation_1d.py
- simpeg/electromagnetics/utils/em1d_utils.py
- simpeg/utils/code_utils.py
- tests/em/em1d/test_EM1D_TD_general_fwd.py
- tests/em/em1d/test_utils.py
- tests/utils/test_report.py
`empymod` is a pretty heavy dependency for the functionality we are using from it. This removes the dependency and instead uses `libdlf` to get the filters, and a streamlined `get_splined_dlf_points` for our internal use.
I say `empymod` is a heavy dependency because it in turn relies on `numba`.
> Remove empymod dependency

- simpeg/electromagnetics/time_domain/sources.py
- tests/em/tdem/test_TDEM_crosscheck.py
Bugfix so that the initial fields produced for `db/dt`, `dh/dt`, from the B field or H field simulations are zero. There was previously a bug where we set the electric source term to `Zero()` when infact it should have been evaluated. This would only effect `db/dt` (or `dh/dt`) that were measured before the first time-step, but it also impacted visualizations of the fields. 
To catch this issue, I have extended our cross-check tests for tdem simulation to also include an evaluation of the data at t=0. Running this test on the current main version of SimPEG will fail. 
As an example, using the `tdem.simulation.Simulation3DMagneticFluxDensity` for a loop source and plotting db/dt gives: 
**Before the bugfix**
Crazy db/dt! 
**After**
Zero -- as it should be
expect …
> Bugfix for TDEM magnetic dipole sources 

- simpeg/potential_fields/base.py
Add missing docstring to the `n_processes` property in potential field simulation classes.
The missing docstrings were raised by @thibaut-kobold in Mattermost.
> Add docstring to `n_processes` in potential field simulations

- simpeg/regularization/pgi.py
Avoid slow for loops over numpy arrays in PGI derivs. The associated changes in the __call__ can also be sped up but I left them as is for now to show the deriv tests work.
Speed up dot products in the derivative methods of the PGI regularization classes by making use of Numpy functions instead of for loops that perform a significant number of iterations.
> Speed up most commonly used deriv/deriv2 in PGI

- simpeg/regularization/pgi.py
Change the `__call__` method in PGI smallness to avoid for loops through numpy arrays. Fix the docstring to reflect that physical properties can still be correlated if `approx_eval=True` and `approx_gradient=True`.
> Improve dot products in `PGIsmallness.__call__` and update docstring

- examples/10-pgi/plot_inv_1_PGI_Linear_1D_joint_WithRelationships.py
Updates the PGI plotting example for matplotlib 3.10 removals.
> update PGI Example plotting script for deprecated collections

- .github/workflows/pull_request.yml
- .github/workflows/zizmor.yml
- simpeg/foobar.py
Set `permissions` in Action workflows to solve zizmor's complains about excessive permissions for the `GITHUB_TOKEN`.
Some references:
* [zizmor docs for the `excessive-permissions` audit rule](https://woodruffw.github.io/zizmor/audits/#excessive-permissions)
* [Defining access for the GITHUB_TOKEN permissions](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions)
* [Controlling permissions for `GITHUB_TOKEN`](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token)
> Set `permissions` in Actions to avoid zizmor's `excessive-permissions`

- simpeg/electromagnetics/utils/waveform_utils.py
The function `scipy.integrate.quadrature` was removed in scipy v1.15.0 in favor of `scipy.integrate.quad`. This function is available in 1.8 so no need to update the minimum required scipy version.
> Fix for removed quadrature function on new scipy versions

- simpeg/data_misfit.py
- tests/base/test_data_misfit.py
Make `BaseDataMisfit.residual` to raise an error if the simulation returns an array with `nan`s and/or `inf`s after calling the `dpred` method. Add tests to check if the errors are correctly raised. Remove error in case `BaseDataMisfit.data` is `None`: the `data` setter method doesn't allow `BaseDataMisfit.data` to be `None`, therefore the error will never be raised.
TODO:
> Raise errors if dpred in `BaseDataMisfit` has nans

- .github/ISSUE_TEMPLATE/bug-report.yml
Correctly use the "bug" label in the issue template for bug reports.
> Fix usage of "bug" label in bug report template

- simpeg/electromagnetics/base_1d.py
- simpeg/electromagnetics/frequency_domain/simulation_1d.py
- tests/em/em1d/test_EM1D_FD_fwd.py
- tests/em/em1d/test_EM1D_TD_general_jac_layers.py
Allows multiple locations for EM1D receivers
Closes #1629
Allows for multiple locations in a single receiver for both 1D layered FDEM and TDEM simulations (and adds some simple testing to ensure it works).
> Em1d multiple rx locs

- tests/pf/test_forward_Grav_Linear.py
Avoid using `dpred` in the gravity test that might lead to confusion. When the mapping is not a linear function, the `J @ m` is just a first order approximation of the forward model and not equal to the `dpred`.
> Improve variable names in gravity test

- .github/zizmor.yml
Add a new `.github/zizmor.yml` configuration file that allows zizmor to use tags to pin the two reviewdog actions we currently use: `reviewdog/action-flake8` and `reviewdog/action-black`.
> Configure zizmor to pin reviewdog actions with tags

- simpeg/potential_fields/gravity/survey.py
- simpeg/potential_fields/magnetics/simulation.py
- simpeg/potential_fields/magnetics/survey.py
- tests/pf/test_components.py
- tests/pf/test_forward_PFproblem.py
Deprecate the `components` properties in potential field surveys. These properties weren't returning the expected output. Since receivers within the same survey can have different components, returning the components of the first receiver is misleading.
Fixes #1609
> Deprecate `components` in potential field surveys

- simpeg/potential_fields/magnetics/simulation.py
- tests/pf/test_forward_Mag_Linear.py
Make use of `survey.nD` instead of just using the total number of receiver locations. Add the special case where `is_amplitude_data` is `True`. Add tests.
> Fix bug on magnetic simulation `nD` property

- simpeg/electromagnetics/natural_source/simulation.py
- tests/em/nsem/forward/test_getJ_not_implemented.py
Overwrite the `getJ` method of the NSEM 1D finite volume simulations so they raise a `NotImplementedError`. Add tests for the new errors.
First step towards addressing #1541.
> Raise NotImplementedError on getJ for NSEM 1D simulations

- simpeg/potential_fields/gravity/_numba_functions.py
- simpeg/potential_fields/gravity/simulation.py
- simpeg/potential_fields/magnetics/_numba_functions.py
- simpeg/potential_fields/magnetics/simulation.py
- tests/pf/test_forward_Grav_Linear.py
- tests/pf/test_forward_Mag_Linear.py
Declutter the potential field simulations by defining dictionaries with Numba functions for gravity and magnetics. This way the simulations don't need to define private attributes for each one of them: they can just get the desired function in a single line. Raise `NotImplementedError` on diagonal of G.T @ G when `"forward_only"` and using `geoana` as engine. Specify which type of error should be raised in the `xfail` parameters present in some tests.
> Clean up Numba functions for potential field simulations

- simpeg/__init__.py
Add missing classes in `maps.py` to the API Reference.
Fixes #1671
> Add missing map classes to the API reference

- simpeg/electromagnetics/natural_source/simulation_1d.py
- tests/em/nsem/forward/test_Recursive1D_VsAnalyticHalfspace.py
The recursive solution exclusively computes the impedance, apparent resistivity and/or phase of the Zxy impedance at all frequencies. In the convention adopted by SimPEG, Zxy is in the lower-left quadrant of the complex plane. Using np.atan(imag/real) results in phase values between -90 and +90 which is wrong.
Suggest we use ``np.angle`` instead.
> Fix bug in phase for recursive 1d NSEM simulation

- .ci/azure/setup_env.sh
- .ci/environment_test.yml
Use `conda-forge` instead of `defaults` channel when setting up the environment in Azure pipelines. This avoid us having to accept Anaconda's ToS. Fix bash syntax when defining `is_azure` variable. Use `python-build` instead of `build` in `.ci/azure/setup_env.sh` since `build` is not available in `conda-forge`.
This PR fixes tests not running in Azure due to unaccepted ToS.
> Use conda-forge as only channel in Azure pipelines

- examples/07-nsem/plot_fwd_nsem_MTTipper3D.py
- simpeg/electromagnetics/natural_source/utils/data_utils.py
- simpeg/electromagnetics/natural_source/utils/test_utils.py
- tests/em/nsem/forward/test_1D_finite_volume.py
- tests/em/nsem/forward/test_Recursive1D_VsAnalyticHalfspace.py
- tests/em/nsem/inversion/test_BC_Sims.py
- tests/em/nsem/inversion/test_Problem1D_Adjoint.py
- tests/em/nsem/inversion/test_Problem1D_Derivs.py
- tests/em/nsem/inversion/test_complex_resistivity.py
Replace the deprecated `PointNaturalSource` and `Point3DTipper`  NSEM receiver classes for their new counterparts (`Impedance` and `Tipper`) in examples and tests.
>     Use `Impedance` and `Tipper` in examples and tests

- simpeg/electromagnetics/natural_source/receivers.py
- simpeg/electromagnetics/natural_source/utils/test_utils.py
- tests/em/nsem/forward/test_receiver_eval.py
Fixes bug #1691 
Make `Impedance.eval()` to return an array full of zeros in case that the receiver's orientation is `"xx"` or "`yy`" and the mesh is not 3D. This solves a bug that was causing the NSEM 1D simulation to error out after trying to cast the output of `eval()` into an array. Add test for the bugfix.
Fixes bug #1691 
Eval for xx and yy receivers outputs a float instead of an appropriate array.
> Fix bug on `Impedance.eval` when orientation is "xx" or "yy"

- .ci/environment_test.yml
- CITATION.rst
- docs/conf.py
- docs/content/user-guide/getting-started/about-simpeg.rst
- docs/content/user-guide/getting-started/big_picture.rst
- docs/content/user-guide/getting-started/citing.rst
- docs/content/user-guide/index.rst
- docs/index.rst
- environment.yml
- pyproject.toml
Create a custom RST landing page using `sphinx-design` that includes cards to the main sections of the docs. Move some content from the old landing page (present in the `README.rst`) into new sections in the User Guide: `citing.rst` and `about-simpeg.rst`.
Replaces the usage of the `README.rst` as the landing page of the docs. It's
better to keep them as separate documents with different purposes: the
`README.rst` should be more intended for contributors, while the landing page
of the docs should primarily target users and help them navigate through the
docs.
> Improve landing page of docs

- docs/content/user-guide/how-to-guide/move-mesh-to-survey.rst
- docs/content/user-guide/index.rst
Add a new page to the How to Guide that explains how to move a mesh to a given survey area. This is handy when working with real-world data, whose coordinates are going to be given in projected plain coordinates.
> Add How to Guide page on moving mesh to survey area
