simpeg/simpeg

.travis.yml
SimPEG/Maps.py
SimPEG/Mesh/CylMesh.py

Minor updates to CylMesh and anaconda to make travis pass.

Anisotropy

---

SimPEG/Tests/TestUtils.py
SimPEG/Tests/test_utils.py
SimPEG/Utils/matutils.py

added a test for the diagonal estimator (and some documentation)

Test diag est

---

SimPEG/Mesh/CylMesh.py
SimPEG/Mesh/DiffOperators.py
SimPEG/Mesh/TensorMesh.py
SimPEG/Mesh/View.py
SimPEG/Tests/test_cylMesh.py

Can interpolate onto a cartesian mesh from a cyl mesh.

cyl mesh interpolation

---

SimPEG/Survey.py

- removed knownSrc from Survey
- each source should now be its own class

Removed knownSrc

---

SimPEG/Maps.py
SimPEG/Models.py
SimPEG/PropMaps.py
SimPEG/Tests/test_PropMaps.py
SimPEG/Tests/test_maps.py
SimPEG/Utils/PropMaps.py
SimPEG/Utils/codeutils.py

Simple instantiation of property maps:
```python
class MyPropMap(Maps.PropMap):
sigma = Maps.Property("Electrical Conductivity", defaultInvProp=True)
mu    = Maps.Property("Magnetic Permeability", defaultVal=mu_0)
```
Will give you the following:
```python
myPropMap = MyPropMap([('sigma', expMap)])
model = myPropMap(vector)
model.sigma == np.exp(vector)
model.mu == mu_0
model.sigmaModel == vector
model.sigmaDeriv is not None
model.muModel is None
model.muDeriv is None
```

Property Maps

---

SimPEG/Fields.py
SimPEG/Tests/test_Fields.py

Fields should always be given a source list

Fields src list

---

SimPEG/Regularization.py

@sgkang, @grosenkj : is this more clear?

broke apart smoothness and smallness terms

---

.travis.yml

using `sudo: false` for travis

try running travis on new framework

---

SimPEG/Tests/test_Zero.py
SimPEG/Utils/matutils.py

These should work with sparse matrices and numpy arrays.
```python
z = Zero()
z*A == 0
o = Identity()
o*A == A
```
Addresses #119

Zero and Identity - Useful for writing derivatives.

---

.travis.yml
SimPEG/Examples/DCfwd.py
SimPEG/FLOW/Examples/Celia1990.py
SimPEG/FLOW/Examples/__init__.py
SimPEG/FLOW/Richards/Empirical.py
SimPEG/FLOW/Richards/RichardsProblem.py
SimPEG/FLOW/Richards/__init__.py
SimPEG/FLOW/__init__.py
docs/flow/index.rst
docs/index.rst
tests/flow/__init__.py
tests/flow/test_Richards.py
tests/flow/test_examples.py

Merged in the other repositiory

SimPEG.FLOW

---

SimPEG/Utils/ModelBuilder.py

added model builder to create layered model. 
untested and no error checking yet

Layered Model

---

SimPEG/Mesh/TreeMesh.py

#185 
This will yell at you if you try to create the TreeMesh without first running the `setup.py`

Addresses #183: Import errors for tree mesh

---

SimPEG/Regularization.py

Possible first step to generalize things for issue #188

Generalize mapPair

---

.travis.yml
tests/em/fdem/inverse/derivs/test_FDEM_derivs.py

This should address #162
I have put a bunch of work into pymatsolver to get it working on ubuntu and mac.
https://github.com/rowanc1/pymatsolver

Speed up the tests with pymatsolver.

---

SimPEG/EM/FDEM/FDEM.py

clean solver in fields, Jvec, Jtvec for FDEM

add Ainv.clean() to fdem fields, jvec, jtvec

---

SimPEG/Examples/EM_TDEM_1D_Inversion.py
SimPEG/Examples/__init__.py
docs/examples/EM_TDEM_1D_Inversion.rst

- this is a TDEM inversion (not FDEM)

Update and rename EM_FDEM_1D_Inversion.py to EM_TDEM_1D_Inversion.py

---

SimPEG/EM/FDEM/FDEM.py
SimPEG/EM/FDEM/SurveyFDEM.py
SimPEG/EM/TDEM/BaseTDEM.py
SimPEG/EM/TDEM/SurveyTDEM.py
SimPEG/Examples/Inversion_Linear.py
SimPEG/Examples/MT_3D_Foward.py
SimPEG/FLOW/Richards/RichardsProblem.py
SimPEG/MT/BaseMT.py
SimPEG/MT/SurveyMT.py
SimPEG/Survey.py
tests/em/tdem/test_TDEM_b_DerivAdjoint.py
tests/em/tdem/test_TDEM_b_MultiSrc_DerivAdjoint.py
tests/mt/test_Problem1D_againstAnalyticHalfspace.py
tests/mt/test_Problem3D_againstAnalytic.py

Evaluate receivers:  
- rx.projectFields --> rx.eval
- rx.projectFieldsDeriv --> rx.evalDeriv
This change is not backwards compatible (but should be internal??) 
Closes #247

rx.projectFields --> rx.eval

---

SimPEG/EM/FDEM/FDEM.py
SimPEG/EM/FDEM/SrcFDEM.py

instead of specifying 'EF' or 'FE' for specifying equation locations, specify which formulation we are using 'EB' or 'HJ'. closes #258

eqlocs --> formulation in em

---

SimPEG/EM/FDEM/SrcFDEM.py
SimPEG/EM/Utils/testingUtils.py

Make source integration default false for Raw Vec sources (assuming you are providing something that is already integrated), can be changed with the kwarg `integrate`. @grosenkj

make integrate = False default for all sources

---

SimPEG/Directives.py
SimPEG/MT/Utils/ediFilesUtils.py
tests/mt/test_Problem3D_againstAnalytic.py

Fixed osr import in ediFilesUtils.
Moved the import into projection functions which should only import on calling of the function.
Also fixed a small boolean error in Directives.

Fixing Issue #290

---

SimPEG/Directives.py

- use a `chifact` and a `phi_d_star` to define target misfit. ie
```
target = chifact * phi_d_star
```
to close #266

Target Misfit

---

SimPEG/EM/FDEM/FieldsFDEM.py
SimPEG/EM/FDEM/RxFDEM.py

Changes in FieldsFDEM.py, RxFDEM.py

Implementation for Inverting Secondary B field

---

.gitignore
SimPEG/Examples/DC_Analytic_Dipole.py
SimPEG/Examples/Maps_ComboMaps.py
SimPEG/Examples/Maps_Mesh2Mesh.py
SimPEG/Examples/Utils_surface2ind_topo.py
SimPEG/Examples/__init__.py
docs/content/api_core/api_Maps.rst
docs/content/examples/Inversion_IRLS.rst
docs/content/examples/Maps_ComboMaps.rst
docs/content/examples/Maps_Mesh2Mesh.rst

Also fixed plotting codes to show the plots by default.

Mesh2Mesh and Combo Map examples.

---

SimPEG/EM/Static/DC/BoundaryUtils.py
SimPEG/EM/Static/DC/FieldsDC.py
SimPEG/EM/Static/DC/FieldsDC_2D.py
SimPEG/EM/Static/DC/ProblemDC.py
SimPEG/EM/Static/DC/ProblemDC_2D.py
SimPEG/EM/Static/DC/RxDC.py
SimPEG/EM/Static/DC/SrcDC.py
SimPEG/EM/Static/DC/SurveyDC.py
SimPEG/EM/Static/DC/Utils.py
SimPEG/EM/Static/DC/__init__.py
SimPEG/EM/Static/IP/ProblemIP.py
SimPEG/EM/Static/SIP/ProblemSIP.py
docs/conf.py
docs/content/dc/index.rst
tests/em/static/test_DC_2D_analytic.py
tests/em/static/test_DC_analytic.py
tests/em/static/test_IP_fwd.py

build docs for dc, some pep8 styling while at it

---

tests/em/static/test_DC_2D_jvecjtvecadj.py
tests/em/static/test_DC_jvecjtvecadj.py
tests/em/static/test_IP_jvecjtvecadj.py
tests/em/static/test_SIP_jvecjtvecadj.py
tests/pf/test_grav_inversion_linear.py

set seeds in tests that use random vectors

set random seeds in tests

---

SimPEG/EM/FDEM/ProblemFDEM.py
SimPEG/MT/BaseMT.py

Merging into the correct branch. See #406 for original comments.

Remove the datapair

---

SimPEG/Utils/io_utils.py

only import vtk in needed functions in io_utils

vtk import io_utils

---

SimPEG/EM/TDEM/SrcTDEM.py

cleanup assertion on tdem srcs

---

tests/em/fdem/forward/test_FDEM_analytic_Dipoles.py

Working to isolate repeated code in the test_FDEM_analytic_Dipoles.py and turn them into functions. This currently includes 
- plotting code
- printing the error log
- setting up the mesh
TODO's
@micmitch: have a look and see what you think of these changes. If you would be game to take care of isolating and sharing the re-used pieces of setup code in each class, that would make this suite of tests more transparent to someone reading the code. 
This is a great suite of tests and will be nice to have in SimPEG!

Analytics cleanup

---

docs/content/api_core/api_installing.rst

update link for numpy for matlab users

---

SimPEG/EM/Static/DC/FieldsDC.py

divide by volume for J calc on nodal fields

bug fix in nodal j calc

---

.travis.yml

according to ContinuumIO/anaconda-issues#1090 the conda fix is now live.
closes #435

remove pinned versions of matplotlib, pyqt

---

docs/conf.py

allow retrys for pinging links, increase timeout time

patch linkchecking 

---

SimPEG/Utils/matutils.py
tests/__init__.py
tests/base/__init__.py
tests/em/fdem/forward/__init__.py
tests/em/fdem/inverse/adjoint/__init__.py
tests/em/fdem/inverse/derivs/__init__.py
tests/em/static/__init__.py
tests/em/tdem/__init__.py
tests/flow/__init__.py
tests/mesh/__init__.py
tests/mt/__init__.py
tests/pf/__init__.py
tests/utils/__init__.py
tests/utils/test_Zero.py

Seems that it the `__numpy_ufunc__` flag it is there this is good enough  …
I am actually a bit unsure of why this works.
to see more:
http://docs.scipy.org/doc/numpy-dev/reference/arrays.classes.html#numpy.class.__numpy_ufunc__
Since we have all other functions implemented:
"your __numpy_ufunc__ method will not be called"
I figure if it is a boolean, not a callable, we will figure this out
pretty fast if it starts to fail in the future.
This adds a test to assert that we get a zero back on multiplication.

array * Zero() == Zero()!!

---

docs/app.yaml

upload python source files for `.. plot::` directives 
closes #363

upload .py files on docs 

---

.travis.yml

give travis lots of time to upload to pypi

Patch/travis [no-ci]

---

SimPEG/EM/NSEM/FieldsNSEM.py
SimPEG/EM/NSEM/ProblemNSEM.py
SimPEG/EM/NSEM/RxNSEM.py
SimPEG/EM/NSEM/SrcNSEM.py
SimPEG/EM/NSEM/SurveyNSEM.py
docs/content/examples/FLOW_Richards_1D_Celia1990.rst
tests/em/nsem/forward/test_Problem1D_VsAnalyticHalfspace.py
tests/em/nsem/inversion/test_Problem1D_Derivs.py
tests/em/nsem/inversion/test_Problem3D_Derivs.py

Address some of the codacy issues from https://www.codacy.com/app/lindseyheagy/simpeg/pullRequest?prid=363079
(Note: none of the issues in `Utils` have been address, will be in next NSEM updates)

Fixing NSEM codacy errors

---

SimPEG/Maps.py
tests/base/test_maps.py

Simple projection map to select indices of a model 
cc @fourndo

Projection Map

---

SimPEG/Problem.py
tests/base/test_problem.py

add property stub for the curModel so that an exception is raised if you try to set it
(originally from #475)

curModel property stub

---

SimPEG/PF/GravityDriver.py

Small changes to Grav Driver for Craig's example to be published

Change input file in Gravity Driver

---

SimPEG/Props.py
tests/base/test_Props.py

The release notes are here:
https://github.com/3ptscience/properties/releases/tag/v0.2.3
See #497

Remove default from the private `_get` method in properties.

---

SimPEG/Props.py

Physical property default is only set if the input is not None.
This commit also removes _exclusive_kwargs, which was removed from
properties

Add fdel to Props, take None out of property validation.

---

.travis.yml
SimPEG/EM/NSEM/ProblemNSEM.py
SimPEG/EM/NSEM/SurveyNSEM.py
SimPEG/EM/NSEM/Utils/dataUtils.py
SimPEG/EM/NSEM/Utils/data_viewer.py
SimPEG/EM/NSEM/Utils/loggingUtils.py
SimPEG/EM/NSEM/Utils/plotUtils.py
SimPEG/Examples/EM_NSEM_1D_ForwardAndInversion.py
SimPEG/Survey.py
tests/base/test_SurveyAndData.py

Implementation of Data classes with built-in 
- .standard_deviation
- .floor 
data containers. 
Also has first pass of updates to `NSEM.Data` plot functions and an interactive data viewer.

nsem/dev_dataClass branch into nsem/dev

---

SimPEG/Problem.py
SimPEG/Props.py
tests/base/test_Props.py

I have been working a bit on more sensible errors and suggestions for the HasModel instances:
```python
prob.summary()  # provides a readable summary of what needs to happen on the class
prob.validate()  # validates that the instance is correctly setup
```

Problem summary and validation

---

SimPEG/Utils/matutils.py
tests/utils/test_coordutils.py
tests/utils/test_utils.py

- better string handling for checking which approach is to be used in the diagonal estimator
- whitespace cleanup in diagonal estimator code
- whitespace cleanup in test_Utils.py

whitespace cleanup in testing, cleanup string checking in diagEst

---

SimPEG/Mesh/View.py
docs/conf.py

enable down-sampling prior to plotting (for crazy casing meshes :) )

add down-sampling capability to _plot2DImage

---

SimPEG/Examples/EM_Heagyetal2016_CylInversions.py
SimPEG/Examples/Inversion_Linear.py
SimPEG/Examples/Inversion_Linear_IRLS.py

- Fix the linear example to close #509
- fix title for the cyl inversion

fix title in EM Cyl example, updated linear inversion

---

.travis.yml

remove the 'preview' from the gae deploy. addresses #549

Deploy the docs

---

SimPEG/EM/NSEM/Utils/plotUtils.py
SimPEG/Examples/EM_NSEM_3D_Foward.py

Fixing NSEM 3D forward example by:
- A better mesh/model with adequate padding and visulazation
- Assigning uncertainties to the data
- Plot the data

Fixing up 3D NSEM example

---

SimPEG/Regularization.py
tests/base/test_regularization.py

- add back the volume term in the small, smooth contributions
- use the square root of the cell weights as the diag of the W matrix cc @fourndo

Volumes in Regularization

---

SimPEG/Directives.py
SimPEG/Inversion.py
requirements_dev.txt
tests/base/test_directives.py

- changes from #580 onto the objective function branch (as per #578). 
- `BaseDirective` has a method `validate(self, directiveList=None)` which returns `True` by default
-  `DirectiveList` has a method `validate(self)` that goes through the directive list and validates each one
- `InvProb` runs the directive list validation on setter

directive validation

---

SimPEG/EM/TDEM/FieldsTDEM.py

- remove the use of inplace addition s += something in the TDEM Fields object

numpy upgrades

---

.travis.yml

update travis so that deployments are only on master as per #651

Travis deploys on dev only

---

SimPEG/EM/Static/DC/SurveyDC.py

- move the if else so that we don't have to repeat the rx if / else statement in getABMN
@sgkang: would you be willing to take a look?

simplify getABMN

---

SimPEG/EM/NSEM/FieldsNSEM.py

Minor typo in docs

---

tests/em/vrm/vrmfwd_tests.py

This is a temporary change to vrmfwd_tests.py so that master doesn't fail. This test has been updated in along with code as part of PR #708

Temporary change to VRM tests

---

README.rst

Add buttons to the SimPEG Slack and Google group in the Readme.rst

Add buttons to the SimPEG Slack and Google group in the Readme.rst

---

docs/content/basic/practices.rst

A just read through part of the docs yesterday, so I'll push some typos. I hope that is fine.

Typo in practices-doc

---

.travis.yml

Bug contour plots

---

SimPEG/EM/Static/Utils/StaticUtils.py

import matlib explicitly as in numpy 1.16, it isn't imported in the numpy namespace be default

numpy matlib import 

---

README.rst

- add youtube badge
- add Google logo
- respect color recommendations (see https://simpleicons.org/)

add youtube badge to readme

---

SimPEG/Optimization.py

Fixes mis-written variable used in message output. 
Small fix while trying out PRs for the first time.

fixes an attribute error in optimization

---

AUTHORS.rst

Just added my name to AUTHORS.rst

add Devin to contrib

---

SimPEG/PF/Gravity.py
SimPEG/PF/Magnetics.py

- Revert to auto chunking by rows
- Return G instead of load it and overwrite instead of delete and write

MagDev_DF_Dask auto chunk update

---

SimPEG/regularization/regularization_mesh.py

Small fix of the `mkvc` utils call

Small fix for regularization_mesh

---

SimPEG/data_misfit.py
SimPEG/directives.py
SimPEG/electromagnetics/static/resistivity/simulation.py
SimPEG/inverse_problem.py
SimPEG/simulation.py

@JKutt Can you give it a try on your side?
I added an option to set the `max_chunk_size` on the simulation object. Otherwise, it uses dask default (128Mb).
Once you've merge it in, I will start looking at the Tile part.
Cheers

Simulation jk df

---

SimPEG/Utils/modelutils.py

Resolve #832 
fix indexing bug in surfac2ind_topo
Thanks to @yezhengkai for finding it out.

fix bug in surfac2ind_topo

---

SimPEG/electromagnetics/utils/testing_utils.py
tests/em/fdem/muinverse/test_muinverse.py

fix the FDEM testing utils bug described in #862, update the test_muinverse to conform to current API

simulation fdem testing bug 

---

SimPEG/flow/richards/simulation.py
SimPEG/simulation.py

This avoids an import error on initialization of SimPEG.

Import SolverLU straight from utils.

---

SimPEG/electromagnetics/frequency_domain/sources.py

Add a missing comma to L 175 between "frequency" and "** kwargs".

Missing comma fixed

---

SimPEG/directives.py
SimPEG/electromagnetics/static/utils/static_utils.py

simple patch to remove the printing of the filename if we are not actually saving the file

only print the filename if we are going to save the dictionary on disk

---

SimPEG/electromagnetics/static/resistivity/fields_2d.py

Charge bug fix for 2D cell centered DC field

---

SimPEG/electromagnetics/static/utils/static_utils.py

This one was on me on the logic re-do for the transform 2020 conference. This should fix that error now.

bug fix for 3D tensor mesh drape topo.

---

.travis.yml
tests/em/fdem/muinverse/test_muinverse.py

- improve tolerances on the mu inversion testing
- update the test to use the simulation API

Mu Inversion Test for FDEM

---

SimPEG/simulation.py

Resolve #933 
Mapping was not taken into account in `linearSimulation`.

fix mapping in LinearSimulation

---

SimPEG/potential_fields/gravity/simulation.py
SimPEG/potential_fields/magnetics/simulation.py
SimPEG/utils/__init__.py
SimPEG/utils/io_utils.py
SimPEG/utils/io_utils/__init__.py
SimPEG/utils/io_utils/io_utils_general.py
SimPEG/utils/io_utils/io_utils_pf.py
tests/utils/test_io_utils.py

This pull request tackled a couple issues:
1. The IO for potential fields can only read and write dobs. It can now read and write survey and dpred.
2. The forward mag problem was not always accurate for survey locations directly above edges and especially nodes. A new strategy and tolerances have been used to improve numerical accuracy.

Improve mag3d computation over node locations and more versatile pf IO

---

SimPEG/electromagnetics/natural_source/receivers.py
SimPEG/electromagnetics/natural_source/simulation.py
tests/em/nsem/inversion/test_complex_resistivity.py

update derivatives and adjoint for apparent resistivity and phase receivers

Apparent resistivity and phase receivers 

---

SimPEG/electromagnetics/frequency_domain/fields.py
SimPEG/electromagnetics/frequency_domain/simulation.py
SimPEG/electromagnetics/natural_source/receivers.py
SimPEG/electromagnetics/natural_source/simulation.py
SimPEG/electromagnetics/natural_source/sources.py
SimPEG/fields.py
SimPEG/maps.py
SimPEG/survey.py
SimPEG/utils/io_utils/io_utils_pf.py
SimPEG/utils/model_utils.py
docs/conf.py
docs/content/release/0.14.3-notes.rst
docs/content/release/index.rst
tests/utils/test_io_utils.py

This PR updates the fields, and sources to handle multiple field outputs per source, (i.e. both polarizations of an MT source).
The Rx eval currently runs (but I didn't extensively test that I got the hx_px, hy_py, ex_px, etc all in the correct order, but I think it's right). This eval should be easy to extend to the other receiver classes

PR for updated fields

---

SimPEG/electromagnetics/natural_source/fields.py
SimPEG/electromagnetics/natural_source/simulation.py
SimPEG/electromagnetics/natural_source/simulation_1d.py
tests/em/nsem/forward/test_1D_finite_volume.py

Implementation of 1D finite volume solutions that use dirichlet boundary conditions on the top and bottom of the mesh. The `Simulation1DElectricField` discretizes the electric field at cell centers (which corresponds to the TE mode in 2D) while the `Simulation1DMagneticFluxDensity` discretizes the magnetic flux density at cell centers (which corresponds to the TM mode in 2D).

1D Finite volume implementation of the NSEM problem

---

SimPEG/electromagnetics/natural_source/sources.py
SimPEG/electromagnetics/natural_source/utils/source_utils.py

Generalize background code to also handle OcTree meshes

Simulation mt tree

---

SimPEG/dask/data_misfit.py
SimPEG/dask/electromagnetics/static/resistivity/simulation.py
SimPEG/dask/electromagnetics/static/sim_utils.py
SimPEG/dask/inverse_problem.py
SimPEG/dask/objective_function.py
SimPEG/dask/optimization.py
SimPEG/dask/potential_fields/base.py
SimPEG/data_misfit.py
SimPEG/directives.py
SimPEG/electromagnetics/static/resistivity/simulation.py
SimPEG/inverse_problem.py
SimPEG/maps.py
SimPEG/optimization.py
SimPEG/utils/drivers/tile_driver.py
examples/04-dcip/plot_inv_dcip_poledipole_3D_tilied_inversion_onesphere.py

adding in further dask methods to inverse problem for tiled dc problem + tiled dc example

added dask tiled version methods for the inversion_problem object

---

README.rst

Update readme.rst to remove travis icon

Replace Travis Icon by Azure in Readme

---

SimPEG/potential_fields/gravity/simulation.py
SimPEG/potential_fields/magnetics/simulation.py

In the getJtJdiag function I believe that self.nD needs to be self.survey.nD.

Bug fix for gravity simulation 

---

SimPEG/dask/electromagnetics/static/induced_polarization/simulation.py
SimPEG/dask/electromagnetics/static/resistivity/simulation.py
SimPEG/electromagnetics/static/induced_polarization/simulation.py
SimPEG/electromagnetics/static/induced_polarization/simulation_2d.py
SimPEG/electromagnetics/static/resistivity/receivers.py
SimPEG/electromagnetics/static/resistivity/simulation.py
SimPEG/electromagnetics/static/resistivity/simulation_2d.py
SimPEG/electromagnetics/static/resistivity/survey.py
docs/conf.py
tests/base/test_Fields.py
tests/em/static/test_DC_2D_analytic.py
tests/em/static/test_DC_2D_jvecjtvecadj.py
tests/em/static/test_IP_2D_fwd.py
tests/em/static/test_IP_fwd.py
tutorials/05-dcr/plot_inv_2_dcr2d.py
tutorials/05-dcr/plot_inv_2_dcr2d_irls.py
tutorials/06-ip/plot_inv_1_dcip2d.py

implements testing on apparent changeability data for the IP in 2D and 3D,
Enabled to find runtime bug for 2D IP, however accuracy of the 2D apparent changeability data seems off.

Fixing 2D IP bug

---

SimPEG/data.py
tests/base/test_data.py

As discussed in yesterdays meeting. I only done the change in the definition so far, so we have to see/test what fails, if at all.
Feel free to push to this branch to update/improve things.

Change definition of standard deviation

---

SimPEG/electromagnetics/frequency_domain/simulation_emg3d.py

@sgkang , let's merge my branch `emg3d-solver` into SimPEG - it seems to cause too much confusion. Unfortunately it means that all SimPEG tests will run with every commit.

emg3d solver

---

SimPEG/electromagnetics/frequency_domain/simulation.py
SimPEG/electromagnetics/natural_source/utils/data_utils.py

A quick change to catch an internal deprecation of `.freqs` instead of `.frequencies`

rename .freqs to frequencies

---

docs/content/release/0.15.1-notes.rst
docs/content/release/index.rst

0.15.1 release notes

---

SimPEG/simulation.py

This is related to previous PR #1022 by @prisae.

fix standard deviation in make synthetic data

---

SimPEG/regularization/__init__.py
SimPEG/regularization/jtv.py
tests/base/test_jtv.py
tests/base/test_regularization.py

Joint total variation

---

SimPEG/directives/sim_directives.py
docs/content/basic/getting_started_developers.rst
docs/content/release/0.16.0-notes.rst

This PR is for the 0.16.0 Release Notes

0.16.0 Release Notes

---

docs/_templates/footer.html

remove disqus from the footer because all we got was spam! 🍔

remove disqus from the footer

---

SimPEG/_EM/Static/SP/ProblemSP.py

I assume this was a typo @jcapriot

Fix type (`solver_opts`, not `solver_spts`)

---

SimPEG/electromagnetics/natural_source/simulation.py

Fix for broken TensorMesh

---

SimPEG/regularization/sparse.py
tests/base/test_regularization.py

Adds more flexibility to setting the norms on sparse data with different data types by attempting to cast them to floats.
Address #1116

Make sparse regularization use the validator functions

---

SimPEG/directives/directives.py

This Is a small bug fix for a few of the common directives to work with a single regularization function.

Single reg directive fix

---

SimPEG/electromagnetics/frequency_domain/sources.py
SimPEG/electromagnetics/time_domain/sources.py
SimPEG/regularization/base.py
SimPEG/regularization/pgi.py
SimPEG/regularization/regularization_mesh.py
azure-pipelines.yml
docs/content/release/0.14.0-notes.rst
docs/content/release/0.14.1-notes.rst
docs/content/release/0.14.2-notes.rst
docs/content/release/0.14.3-notes.rst
docs/content/release/0.15.0-notes.rst
docs/content/release/0.15.1-notes.rst
docs/content/release/0.15.2-notes.rst
docs/content/release/0.16.0-notes.rst
docs/content/release/0.17.0-notes.rst
docs/content/release/0.18.0-notes.rst
docs/content/release/index.rst
environment_test.yml
setup.py

Adding release notes for the next SimPEG version!

0.18.0 Release Notes

---

.azure-pipelines/matrix.yml
azure-pipelines.yml
docs/content/release/0.18.0-notes.rst
docs/content/release/0.18.1-notes.rst
docs/content/release/index.rst
environment_test.yml

Staging for the 0.18.1 patch release, with notes

0.18.1 release

---

.flake8
Makefile
azure-pipelines.yml
environment_test.yml
requirements_dev.txt
requirements_style.txt

Run style checks using flake8 and some of its plugins. Add a new
`.flake8` configuration file to tweak the style checks. Add a new
`check` target in the `Makefile`. Create a new pipeline in Azure to
automatically run style checks on every PullRequest. Add new required
packages to `environment_test.yml` and to a new
`requirements_style.txt`.

Run style checks in Azure Pipelines

---

SimPEG/potential_fields/base.py
tests/pf/test_forward_Grav_Linear.py

Adds a simple property for controlling the number of processes created during the potential field forward simulations.

Add property to control number of processes created.

---

SimPEG/potential_fields/base.py
tests/pf/test_forward_Grav_Linear.py

Change base potential fields simulation to not use multiprocessing if only using a single thread.

Do not use multiprocessing on single thread.

---

SimPEG/data_misfit.py
SimPEG/objective_function.py

Properly implement the `_has_fields` for data misfit

Fix for _has_fields

---

SimPEG/maps.py
SimPEG/utils/__init__.py
SimPEG/utils/code_utils.py
SimPEG/utils/coord_utils.py
SimPEG/utils/curv_utils.py
SimPEG/utils/mat_utils.py
SimPEG/utils/mesh_utils.py

Change simpeg to not import deprecated discretize functions.

Do not import deprecated discretize utilities

---

.azure-pipelines/matrix.yml
azure-pipelines.yml

Update to more recent codecov script

update codecov script

---

SimPEG/__init__.py
SimPEG/maps.py
tests/base/test_maps.py

Add a simple (yet flexible) `LinearMap`.

Linear mapping

---

SimPEG/regularization/base.py
tests/base/test_regularization.py

Fix length scale getters

---

SimPEG/maps.py
tests/base/test_maps.py

Add a simple property to determine if a mapping is linear.

Add a linearity property to mappings

---

.azure-pipelines/matrix.yml
azure-pipelines.yml
docs/conf.py
environment_test.yml
tests/base/test_utils.py
tests/em/tdem/test_TDEM_DerivAdjoint_RawWaveform.py
tests/em/tdem/test_TDEM_DerivAdjoint_galvanic.py
tests/em/tdem/test_TDEM_crosscheck.py
tests/flow/test_Richards.py
tests/pf/test_mag_inversion_linear_Octree.py

Updates SimPEG for the latest discretize version (in a backward compatible way)
The next version of discretize changes many of the deprecation calls to actual errors, this PR is to cleanup any possibly missed
updates in SimPEG.

Discretize 0.9.0updates

---

SimPEG/electromagnetics/__init__.py
SimPEG/electromagnetics/analytics/FDEM.py
SimPEG/electromagnetics/static/spontaneous_potential/__init__.py
SimPEG/fields.py
SimPEG/potential_fields/gravity/__init__.py
SimPEG/regularization/__init__.py
SimPEG/regularization/base.py
SimPEG/utils/__init__.py
SimPEG/utils/code_utils.py
SimPEG/utils/io_utils/io_utils_pf.py
SimPEG/utils/model_builder.py
tutorials/07-fdem/plot_fwd_2_fem_cyl.py

Cleans up a few documentation pages.
Removes duplicate documentation of utilities imported from discretize. Also cleans up a few other small documentation errors.

General Doc cleanup

---

docs/content/release/index.rst

Adds the 0.20.0 release notes to the ToC.

Add 0.20.0 release notes to toc

---

docs/_templates/layout.html

- add plausible analytics to SimPEG docs and remove google analytics
- this will require the docs to be re-deployed (ideally as soon as possible so that we aren't losing out on analytics) 
N/A
We were previously using google analytics which imposes more tracking than what we would like. Also, now that google is requiring v4 (which we haven't set up), we are no longer receiving analytics.

add plausible analytics to simpeg docs

---

.azure-pipelines/matrix.yml

Run `pytest` with the `-v` option in Azure Pipelines. In some situations
might be good to know precisely which tests functions are being run and
with which combination of parameters in Azure Pipelines.

Run pytest on Azure with increased verbosity

---

examples/20-published/plot_heagyetal2017_casing.py

Fix a minor flake8 warning in one of the examples that was making the style
checks in GitHub Actions to fail.

Fix minor flake8 warning

---

tutorials/03-gravity/plot_1a_gravity_anomaly.py
tutorials/04-magnetics/plot_2a_magnetics_induced.py
tutorials/05-dcr/plot_fwd_1_dcr_sounding.py
tutorials/05-dcr/plot_fwd_2_dcr2d.py
tutorials/05-dcr/plot_fwd_3_dcr3d.py
tutorials/06-ip/plot_fwd_2_dcip2d.py
tutorials/06-ip/plot_fwd_3_dcip3d.py
tutorials/07-fdem/plot_fwd_1_em1dfm.py
tutorials/07-fdem/plot_fwd_3_fem_3d.py
tutorials/08-tdem/plot_fwd_1_em1dtm.py
tutorials/08-tdem/plot_fwd_3_tem_3d.py
tutorials/12-seismic/plot_fwd_1_tomography_2D.py
tutorials/_temporary/plot_fwd_1_em1dtm_stitched_skytem.py

Change reference to random.rand to random.randn for a centred normal distribution.
Address issue #1298

ISSUE-1298: Use normal distributed noise in example.

---

SimPEG/potential_fields/magnetics/receivers.py
SimPEG/potential_fields/magnetics/simulation.py
tests/pf/test_forward_Mag_Linear.py

This PR adds magnetic forward modelling for the gradient of the TMI, measured when several magnetometers are mounted on the same aircraft. A good example is [the Heli-GT system from SHA geophysics ](https://www.shageophysics.com/#js__scroll-to-section_heli-gt) but many airborne systems have several magnetometers mounted.

Triaxial magnetic gradient forward modelling

---

SimPEG/data_misfit.py
SimPEG/objective_function.py
SimPEG/simulation.py
docs/conf.py

@dccowan Please take a look at this tentative improvement of the documentation. 
Add proper docstrings to classes and methods in `data_misfit.py` and `objective_function.py`.

Documentation improvements for classes in Objective Function Pieces

---

tests/base/test_pgi_regularization.py

fix failing pgi tests in https://github.com/simpeg/simpeg/pull/1326 (I do not have write persmission to the main simpeg repo with this account)
Note: For the record, my opinion about this has not changed from what I expressed in https://github.com/simpeg/simpeg/issues/763, but happy to help as I appear to be in minority.

fix failing pgi tests (factor of half PR)

---

SimPEG/regularization/base.py
SimPEG/regularization/vector.py
tests/base/test_regularization.py

Update test_regularization.py to test vector smoothness derivatives. Update AmplitudeSmoothnessFirstOrder in vector.py so that the call matches the derivative.

Simpeg vector update

---

SimPEG/regularization/base.py
tests/base/test_regularization.py

Fix typo on "simultaneously" in various error messages.

Fix typo in error messages

---

.github/ISSUE_TEMPLATE/bug-report.yml

typo in Reproducible (and a couple other minor edits to simplify the text)
Fix typos in the template for the bug report issue, and simplify the text.

Improvements to template for a bug report issue

---

SimPEG/potential_fields/magnetics/sources.py
SimPEG/potential_fields/magnetics/survey.py
examples/01-maps/plot_sumMap.py
examples/03-magnetics/plot_inv_mag_MVI_Sparse_TreeMesh.py
examples/03-magnetics/plot_inv_mag_MVI_VectorAmplitude.py
examples/03-magnetics/plot_inv_mag_nonLinear_Amplitude.py
examples/_archived/plot_inv_mag_linear.py
tests/base/test_directives.py
tests/dask/test_mag_MVI_Octree.py
tests/dask/test_mag_inversion_linear_Octree.py
tests/dask/test_mag_nonLinear_Amplitude.py
tests/pf/test_forward_Mag_Linear.py
tests/pf/test_forward_PFproblem.py
tests/pf/test_mag_MVI_Octree.py
tests/pf/test_mag_inversion_linear.py
tests/pf/test_mag_inversion_linear_Octree.py
tests/pf/test_mag_nonLinear_Amplitude.py
tests/pf/test_mag_uniform_background_field.py
tests/pf/test_mag_vector_amplitude.py
tests/pf/test_pf_quadtree_inversion_linear.py
tests/pf/test_sensitivity_PFproblem.py
tests/utils/test_io_utils.py
tutorials/04-magnetics/plot_2a_magnetics_induced.py
tutorials/04-magnetics/plot_2b_magnetics_mvi.py
tutorials/04-magnetics/plot_inv_2a_magnetics_induced.py
tutorials/13-joint_inversion/plot_inv_3_cross_gradient_pf.py

Raise error when instantiating a `magnetic.sources.SourceField`. Add test checking if this error is raised. Update docstrings, tests, examples and tutorials to use `UniformBackgroundField` instead. Make `UniformBackgroundField` to raise an error if `parameters` is being  passed to the constructor and add test for it.
Part of the solution for #1302

Replace magnetic SourceField for UniformBackgroundField

---

SimPEG/directives/directives.py
SimPEG/directives/pgi_directives.py
SimPEG/electromagnetics/static/spectral_induced_polarization/run.py
SimPEG/regularization/__init__.py
tests/base/test_regularization.py
tests/em/static/test_SIP_2D_jvecjtvecadj.py

Raise errors when constructing deprecated regularization classes. Add test that checks if those errors are being raised. Replace the removed regularization classes that were still being used in a few pieces of the code and in the tests. Use the new classes instead. Add removed classes to the `IGNORE_ME` list in `test_regularization.py` so other tests don't fail.
Part of the solution for #1302

Remove deprecated regularization classes

---

SimPEG/electromagnetics/static/induced_polarization/run.py
SimPEG/electromagnetics/static/resistivity/run.py
SimPEG/electromagnetics/static/spectral_induced_polarization/run.py
SimPEG/regularization/base.py
SimPEG/utils/model_utils.py
examples/03-magnetics/plot_inv_mag_nonLinear_Amplitude.py
examples/08-vrm/plot_inv_vrm_eq.py
examples/_archived/plot_inv_dcip_dipoledipole_2_5Dinversion.py
examples/_archived/plot_inv_dcip_dipoledipole_2_5Dinversion_irls.py
examples/_archived/plot_inv_grav_linear.py
examples/_archived/plot_inv_mag_linear.py
tests/base/test_correspondance.py
tests/base/test_cross_gradient.py
tests/base/test_jtv.py
tests/base/test_model_utils.py
tests/base/test_regularization.py
tests/dask/test_mag_MVI_Octree.py
tests/dask/test_mag_nonLinear_Amplitude.py
tests/em/static/test_SIP_2D_jvecjtvecadj.py
tests/em/static/test_SIP_jvecjtvecadj.py
tests/pf/test_mag_inversion_linear.py
tests/pf/test_mag_nonLinear_Amplitude.py
tutorials/03-gravity/plot_inv_1a_gravity_anomaly.py
tutorials/05-dcr/plot_inv_2_dcr2d_irls.py
tutorials/05-dcr/plot_inv_3_dcr3d.py
tutorials/06-ip/plot_inv_2_dcip2d.py
tutorials/06-ip/plot_inv_3_dcip3d.py
tutorials/10-vrm/plot_fwd_1_vrm_layer.py
tutorials/13-joint_inversion/plot_inv_3_cross_gradient_pf.py
tutorials/_temporary/plot_4c_fdem3d_inversion.py

Remove the `indActive` argument in constructors of regularization classes, remove the `indActive` attribute and replace them for the supported `active_cells`. Replace the `indActive` argument in the `depth_weighting` function in favor of `active_cells`. Raise errors when those arguments are being passed and add tests checking those errors are being raised. Update code, tests and examples that were still using `indActive`.
Part of the solution for #1302

Replace indActive for active_cells in regularizations

---

.gitignore

Ignore the `docs/sg_execution_times.rst` file generated by Sphinx Gallery when building the docs. It contains the execution times of every example in the gallery. We don't need to version control this file.

Add docs/sg_execution_times.rst to .gitignore

---

SimPEG/potential_fields/gravity/simulation.py

Simplify some of the new methods included with the Numba implementation of the gravity simulation: remove the `_get_cell_nodes` method since we can just rely on the `cell_nodes` method of discretize meshes. Update one inline comment.

Simplify private methods in gravity simulation

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
README.rst
docs/conf.py
docs/content/getting_started/contributing/index.rst
docs/content/getting_started/installing.rst

Replace the links pointing to Slack for links pointing to Mattermost. Changes have been applied to the documentation, the `README.rst` and the issue templates.

Update Slack links: point to Mattermost

---

SimPEG/directives/__init__.py
docs/content/api/SimPEG.directives.rst
docs/content/api/index.rst

List directives in the API Reference under their own "Directives" category.
Fixes 1396

Add directives to the API Reference

---

AUTHORS.rst

Add @ghwilliams @YingHuuu to `AUTHORS.rst`.

Add Ying and Williams to AUTHORS.rst

---

.azure-pipelines/matrix.yml

Adds a publish step on the documentation test so we can download it and view it.

Publish documentation on azure

---

SimPEG/meta/__init__.py

Fixes unintended `dask` hard dependency,

Fix hard dask dependency

---

docs/content/release/0.21.0-notes.rst

Fix rst syntax in the release notes of v0.21.0.
Fixes #1433

Fix rst syntax in release notes for v0.21.0

---

simpeg/__init__.py

Update the copyright year in the init

Update copyright year in __init__.py

---

.azure-pipelines/matrix.yml

Lowercase the `simpeg` package when running tests and generating coverage in Azure pipelines. This way we are  orrectly generating the coverage report for the `simpeg` package.

Lowercase simpeg for generating coverage on Azure

---

.github/ISSUE_TEMPLATE/maintenance.md

Add a new issue template for opening maintenance issues.

Add maintenance issue template

---

docs/content/getting_started/contributing/setting-up-environment.rst

Add instructions to the Contributing to SimPEG pages on how to update the environment once it's already created.

Add instructions to update the environment

---

simpeg/electromagnetics/static/resistivity/receivers.py
simpeg/electromagnetics/time_domain/simulation.py

Fix minor typos in EM docstrings.

Fix typos in EM docstrings

---

simpeg/inverse_problem.py

Include the version of SimPEG being used to run a simulation in the inversion log.
Fixes #1474

Print SimPEG version in the inversion log

---

tests/base/test_objective_function.py

Make use of the `random_seed` arguments in a few objective function tests that were missed in previous PR.
Related to #1448.

Use random seed in missed objective function tests

---

azure-pipelines.yml

This commit should be reverted after checking that everything works fine.
Change the cron time for the nightly builds so we can test the deployment of
the docs. I'll revert this PR after I check that the new deployment of the docs
works fine.

Change cron time to test new deployment of docs

---

azure-pipelines.yml

This reverts commit e322585e74549a0865e8da76ccd568ccbeb1551f.

Revert "Change cron time to test new deployment of docs (#1492)"

---

.github/ISSUE_TEMPLATE/release-checklist.md

Remove new line characters in release checklist so the paragraphs and list items are unwrapped. This improves how GitHub renders the issue template. Minor improvements to Markdown style.

Unwrap lines in release checklist

---

.github/ISSUE_TEMPLATE/release-checklist.md

Improve the instructions to update the `versions.json` file in the release checklist.

Improve instructions to update versions.json

---

docs/_static/versions.json
docs/content/release/0.22.0-notes.rst
docs/content/release/index.rst

Add release notes for v0.22.0. Add new version to `versions.json` file and mark it as the latest.
Related to #1497

Add release notes for v0.22.0

---

docs/_static/versions.json
docs/content/release/0.22.1-notes.rst
docs/content/release/index.rst

Add release noted for v0.22.1, and include them in the releases index. Update `versions.json` file: add v0.22.1 as the latest and preferred version.

Add release notes for v0.22.1

---

docs/content/release/0.22.1-notes.rst

Add #1509 to the release notes for v0.22.1.

Add latest merged PR to release notes for v0.22.1

---

docs/_static/versions.json
docs/content/release/0.22.2-notes.rst
docs/content/release/index.rst

Add release notes for v0.22.2. Add v0.22.2 to `versions.json`.
Related to #1531
> [!IMPORTANT]
> This PR is targeted against the `maintenance/v0.22.x` branch.

Add release notes for v0.22.2

---

examples/03-magnetics/plot_inv_mag_MVI_Sparse_TreeMesh.py
examples/03-magnetics/plot_inv_mag_MVI_VectorAmplitude.py

Rename title of one of the magnetic examples to avoid repeated name and to make it clearer what the example is about. Minor fixes to the rst syntax.

Minor fixes to magnetic examples

---

.ci/environment_test.yml
environment.yml
pyproject.toml
simpeg/potential_fields/magnetics/simulation.py
tests/pf/test_forward_Mag_Linear.py

Allow to compute magnetic gradiometry components using Choclo as the engine in the magnetic integral simulation. Add the new magnetic gradiometry kernels to the list of supported components with Choclo as engine and ensure they are being tested. Constrain minimum version of Choclo to v0.3.0.
**TODO**

Support magnetic gradiometry using Choclo as engine

---

examples/20-published/plot_heagyetal2017_cyl_inversions.py

Replace usage of `seed` argument for `random_seed` in one more example.
Part of #1461

Update usage of `random_seed` in one example

---

examples/01-maps/plot_mesh2mesh.py
simpeg/electromagnetics/static/utils/static_utils.py
simpeg/utils/model_builder.py
tests/utils/test_model_builder.py

Replace `seed` for `random_seed` in `model_builder.create_random_model.` Test the deprecation warnings and errors. Update examples and code with new argument.
Closes #1461

Replace `seed` for `random_seed` in `model_builder`

---

tests/dask/test_IP_jvecjtvecadj_dask.py
tests/em/em1d/test_EM1D_FD_jac_layers.py
tests/em/em1d/test_EM1D_TD_off_jac_layers.py

Adds more `random_seed` arguments
Missed a few the first go through, I think this is all of them.

Add missing seeds

---

.ci/azure/codecov.yml

Uploads all the codecov files at once.

Try uploading all the coverage files at once.

---

docs/content/release/0.23.0-notes.rst
docs/content/release/index.rst

Add changelog for SimPEG v0.23.0.
TODO:

Changlog for v0.23.0

---

docs/_static/versions.json

Add entry for v0.23.0 in `_versions.json`.

Add v0.23.0 to the version switcher

---

docs/content/release/0.23.0-notes.rst

Fix date in release notes

---

simpeg/directives/directives.py
simpeg/optimization.py

UBC style printout on minimizers were never updated for #1326, this fixes that and removes the "factor" property that was used to handle that printout style.
Related to #763
Fixes the UBC style printout

Fix ubcstyle printout

---

.github/ISSUE_TEMPLATE/post-install.yml
docs/content/getting_started/contributing/setting-up-environment.rst
docs/content/getting_started/installing.rst

Apply some improvements to the installation instructions under the Getting Started documentation page. Recommend Miniforge over Anaconda as Python distribution. Remove the admonition that warns about using Python 2.7 to run SimPEG. Replace link to Google Form for one to the Discourse forum. Minor improvements on format and style, with minor changes in wording.

Update installation instructions in docs

---

environment.yml

Since zizmor is now available through conda-forge, we don't need to install it through `pip` when creating a conda environment from `environment.yml`.

Install zizmor through conda-forge in `environment.yml`

---

pyproject.toml

Remove non-supported Python versions and add latest ones.

Update Black's Python versions in `pyproject.toml`

---

.github/ISSUE_TEMPLATE/bug-report.yml

Use shell rendering in the runtime information required in the Bug Report Template.

Use shell rendering in Bug report template

---

docs/conf.py

Fix manual redirect for the index page of the User Guide.

Fix redirect to user guide index page

---

tests/pf/test_equivalent_sources.py

Increase maximum number of iterations in magnetic equivalent sources test.

Set maximum number of iterations in eq sources tests

---

tests/pf/test_forward_Grav_Linear.py

Extend test of the `getJ` method of the gravity simulation: test the transpose of the `J` linear operator.

Test transpose of gravity getJ as linear operator

---

docs/_static/versions.json
docs/content/release/0.24.0-notes.rst
docs/content/release/index.rst

Add release notes for SimPEG v0.24.0, and update the version switcher.
Related to #1652

Add release notes for v0.24.0

---

simpeg/potential_fields/gravity/receivers.py
simpeg/potential_fields/gravity/simulation.py

Adds a description and units for gravity UV component in docstrings.
Changes are made in the following places:
-  https://docs.simpeg.xyz/latest/content/api/generated/simpeg.potential_fields.gravity.Point.html
- https://docs.simpeg.xyz/latest/content/api/generated/simpeg.potential_fields.gravity.Simulation3DIntegral.html
Fixes https://github.com/simpeg/simpeg/issues/1664

Update docstring descriptions for gravity gradient component guv

---

simpeg/directives/_directives.py

Apply some minor improvements to the docs of `UpdateSensitivityWeights`: add admonition, fix usage of the `class` directive, update class names mentioned in the docs, improve list of options for different arguments.

Minor fixes to docs of `UpdateSensitivityWeights`
